// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later

package workspace

// us4b_cred_script_exec_test.go — US-4b: execute the generated
// credential-setup script's sidecar-relocation branch under the REAL
// /bin/sh (the dash-bashism lesson, #933 round 2). The branch is the
// security-relevant delta of this story:
//
//   - sidecar mode (AGENTD_SIDECAR_MODE=1): rt dirs become 0770 (the
//     uid-2000 sidecar's reset() must unlink them via the shared gid)
//     and bootstrap is invoked with the relocated --admin-prompt-out /
//     --allowed-dirs-out flags;
//   - default: no chmod (rt dirs stay 0700 — uid-1000-only writers) and
//     the bare bootstrap invocation.
//
// `workspace-agentd` itself is stubbed via a PATH shim that records its
// argv, so the exact generated bytes run without needing the real binary.

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// us4bSidecarBranch extracts the US-4b relocation branch through the end
// of the script (the branch is last: bootstrap if/else + materialize).
func us4bSidecarBranch(t *testing.T, script string) string {
	t.Helper()
	start := strings.Index(script, "# Design 0051 US-4b")
	require.GreaterOrEqual(t, start, 0, "US-4b branch must exist in the script")
	return script[start:]
}

// us4bBranchResult is what runUS4BBranch observed.
type us4bBranchResult struct {
	// Argvs holds one entry per workspace-agentd invocation, each the
	// argv the shim received (fields joined with spaces).
	Argvs []string
	// RTDir is the sandboxed /sandbox-runtime/rt path whose modes the
	// assertions stat.
	RTDir string
}

// runUS4BBranch executes the extracted branch under /bin/sh with the
// given AGENTD_SIDECAR_MODE value, a sandboxed rt layout, and a
// PATH-shimmed workspace-agentd.
func runUS4BBranch(t *testing.T, sidecarMode string) us4bBranchResult {
	t.Helper()
	if _, err := exec.LookPath("chmod"); err != nil {
		t.Skip("chmod(1) not available on this runner")
	}

	ws := newWorkspaceForSecurity(t)
	r := reconcilerWithAgentd(t)
	pod, err := r.buildPod(context.Background(), ws)
	require.NoError(t, err)
	cred := sidecarInitContainer(pod, credentialSetupContainerName)
	require.NotNil(t, cred)
	script := us4bSidecarBranch(t, cred.Command[2])

	dir := t.TempDir()
	// Sandbox the rt layout the branch chmods; rewrite the absolute path
	// so the chmod lands in the sandbox while the guard + chmod +
	// bootstrap structure stays byte-identical.
	rtDir := filepath.Join(dir, "sandbox-runtime", "rt")
	require.NoError(t, os.MkdirAll(filepath.Join(rtDir, "secrets"), 0o700))
	require.NoError(t, os.MkdirAll(filepath.Join(rtDir, "ssh"), 0o700))

	// PATH shim: records one line per invocation (argv space-joined —
	// the values are controller-controlled constants plus the workspace
	// name, none of which contain spaces) and exits 0.
	shimDir := filepath.Join(dir, "bin")
	require.NoError(t, os.MkdirAll(shimDir, 0o755))
	record := filepath.Join(dir, "argv")
	shim := "#!/bin/sh\n{ printf 'workspace-agentd'; for a in \"$@\"; do printf ' %s' \"$a\"; done; printf '\\n'; } >> " + record + "\nexit 0\n"
	require.NoError(t, os.WriteFile(filepath.Join(shimDir, "workspace-agentd"), []byte(shim), 0o755))

	rewritten := strings.ReplaceAll(script, "/sandbox-runtime/rt", rtDir)

	cmd := exec.Command("/bin/sh", "-c", rewritten)
	cmd.Env = []string{
		"PATH=" + shimDir + ":/usr/bin:/bin",
		"WORKSPACE_ID=" + ws.Name,
		"LLMSAFESPACE_API_URL=http://test:8080",
		"AGENTD_SIDECAR_MODE=" + sidecarMode,
	}
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "branch must run clean under /bin/sh; output:\n%s", out)

	raw, err := os.ReadFile(record)
	require.NoError(t, err, "the shimmed workspace-agentd must have been invoked")
	invocations := strings.Split(strings.TrimSpace(string(raw)), "\n")

	return us4bBranchResult{Argvs: invocations, RTDir: rtDir}
}

func TestUS4B_SidecarBranch_ChmodAndFlagsUnderRealSh(t *testing.T) {
	res := runUS4BBranch(t, "1")

	for _, sub := range []string{"secrets", "ssh"} {
		info, err := os.Stat(filepath.Join(res.RTDir, sub))
		require.NoError(t, err, "rt/%s must exist", sub)
		require.Equal(t, os.FileMode(0o770), info.Mode().Perm(),
			"rt/%s must be group-writable in sidecar mode (uid-2000 reset() unlinks via gid 1000)", sub)
	}
	info, err := os.Stat(res.RTDir)
	require.NoError(t, err)
	require.Equal(t, os.FileMode(0o770), info.Mode().Perm(), "rt/ itself must be group-writable (git-credentials unlink)")

	// bootstrap carries the relocated --out flags; materialize follows.
	joined := strings.Join(res.Argvs, "\n")
	require.Contains(t, joined, "bootstrap")
	require.Contains(t, joined, "--admin-prompt-out /agentd-secrets/admin-prompt.md")
	require.Contains(t, joined, "--allowed-dirs-out /agentd-config/allowed-dirs.json")
	require.Contains(t, joined, "materialize")
}

func TestUS4B_SidecarBranch_DefaultModeUnchangedUnderRealSh(t *testing.T) {
	res := runUS4BBranch(t, "")

	for _, sub := range []string{"secrets", "ssh"} {
		info, err := os.Stat(filepath.Join(res.RTDir, sub))
		require.NoError(t, err)
		require.Equal(t, os.FileMode(0o700), info.Mode().Perm(),
			"single-container mode keeps rt/%s 0700 (uid-1000-only writers)", sub)
	}
	info, err := os.Stat(res.RTDir)
	require.NoError(t, err)
	require.NotEqual(t, os.FileMode(0o770), info.Mode().Perm(), "rt/ must not be chmod'ed in default mode")

	joined := strings.Join(res.Argvs, "\n")
	require.Contains(t, joined, "bootstrap")
	require.NotContains(t, joined, "--admin-prompt-out", "default bootstrap invocation carries no relocation flags")
	require.NotContains(t, joined, "--allowed-dirs-out")
	require.Contains(t, joined, "materialize")
}
