// Hand-written TypeScript types matching Go pkg/types/types.go
// Contract-tested via CI (see §17 of FRONTEND.md)

export interface User {
  id: string;
  username: string;
  email: string;
  role: string;
  active: boolean;
  createdAt: string;
}

export interface AuthConfig {
  registrationEnabled: boolean;
  oidcEnabled: boolean;
  passkeyEnabled?: boolean;
  passkeyDefaultSignup?: boolean;
  ssoProviders?: string[];
  instanceName: string;
  motd?: string;
}

export interface AuthResponse {
  token: string;
  user: User;
}

export interface LoginRequest {
  email: string;
  password: string;
  rememberMe?: boolean;
}

export interface RegisterRequest {
  username: string;
  email: string;
  password: string;
}

export interface WorkspaceListItem {
  id: string;
  name: string;
  userId: string;
  orgId?: string;
  runtime: string;
  storageSize: string;
  createdAt: string;
  updatedAt: string;
  phase?: string;
  imageTag?: string;
  agentVersion?: string;
  defaultModel?: string;
  maxActiveSessions?: number;
  agentNeedsRefresh?: boolean;
  credentialsPendingSince?: string;
  devPreviewEnabled?: boolean;
}

export interface WorkspaceListResponse {
  items: WorkspaceListItem[];
  pagination: { limit: number; offset: number; total: number };
}

export interface ActivateWorkspaceResponse {
  resumed: string;
  suspended?: string;
}

export interface SessionListItem {
  id: string;
  title?: string;
  parentId?: string;
  lastMessageAt?: string;
  messageCount: number;
  status: string;
  lastSeenAt?: string;
  hasUnread: boolean;
  /** Prompt tokens from the last LLM step for this session. undefined = no step completed yet. */
  contextUsed?: number;
  /** Session origin: manual | routine | workflow | api (from session_origins enrichment). */
  origin?: string;
}

/**
 * Returned by GET /workspaces/:id/sessions/active. The `active` field lists
 * session IDs currently running on the workspace, and `maxActive` is the
 * configured concurrency ceiling for that workspace.
 */
export interface ActiveSessionsResponse {
  active: string[];
  maxActive: number;
}

// Shape returned by the opencode agent GET /session/:id (proxied through)
export interface AgentSession {
  id: string;
  title?: string;
  parentID?: string;
  share?: string;
}

export interface WorkspaceStatus {
  phase: string;
  podName?: string;
  endpoint?: string;
  credentialState?: CredentialState;
  agentHealth?: AgentHealth;
  sessions?: AgentSessionInfo[];
  imageTag?: string;
  diskUsedBytes?: number;
  diskTotalBytes?: number;
  memoryUsedBytes?: number;
  memoryTotalBytes?: number;
  contextUsed?: number;
  contextTotal?: number;
}

export interface AgentSessionInfo {
  id: string;
  title?: string;
  status: string; // "idle" | "busy"
  contextUsed?: number;
}

export interface CredentialState {
  available: boolean;
  reason?: string;
  message?: string;
}

export interface AgentHealth {
  status: string;
  providersConfigured?: number;
  agentVersion?: string;
  connected?: string[];
  message?: string;
  lastCheckedAt?: string;
}

export interface MessagePart {
  type: string;
  text?: string;
  name?: string;
  input?: unknown;
  id?: string;
  files?: string[];
  hash?: string;
  toolState?: string;
  toolOutput?: string;
}

export interface Message {
  id: string;
  role: "user" | "assistant";
  parts: MessagePart[];
  createdAt?: string;
  modelID?: string;
}

export interface SendMessageRequest {
  parts: MessagePart[];
  model?: { providerID: string; modelID: string };
  messageID?: string;
}

export interface ApiKey {
  id: string;
  name: string;
  prefix: string;
  createdAt: string;
  lastUsedAt?: string;
}

export interface CreateApiKeyRequest {
  name: string;
}

export interface CreateApiKeyResponse {
  key: string;
  apiKey: ApiKey;
}

export interface ApiError {
  error: string;
  code?: string;
  /**
   * Per-field validation details, keyed by JSON field name (e.g. "slug",
   * "ownerEmail"). Present on 400 responses generated by Gin binding
   * failures via bindingErrorResponse() in the backend. Absent for other
   * 4xx/5xx responses.
   */
  details?: Record<string, string>;
  /**
   * Seconds to wait before retrying. Sent by the proxy on 429 (active-
   * session cap / rate limit) and 503 (workspace restarting — in-place
   * opencode restart for credential reload, OOM, crash, relay injection).
   * Mirrors the HTTP `Retry-After` header value.
   */
  retryAfter?: number;
}

// --- Workspace SSE event types ---
// These match the WorkspaceSSEEvent struct emitted by the backend broker.

export interface WorkspacePhaseEvent {
  type: "workspace.phase";
  phase: string;
}

export interface SessionStatusEvent {
  type: "session.status";
  session_id: string;
  // The proxy synthesizes string "idle" | "busy" for this field.
  // The full retry shape (attempt, message, next, action) is NOT carried here —
  // it travels inside an agent.event wrapper with event_type="session.status".
  status: "idle" | "busy";
}

export interface AgentEvent {
  type: "agent.event";
  event_type: string;
  data: unknown;
}

// --- Agent input request types (Epic 16) ---

export interface QuestionOption {
  label: string;
  description: string;
}

export interface QuestionInfo {
  question: string;
  header: string;
  options: QuestionOption[];
  multiple?: boolean;
}

export interface QuestionRequest {
  id: string;
  session_id: string;
  /**
   * Top-level session in the parent chain. Equals session_id for top-level
   * sessions; for subagent/subtask sessions (e.g. opencode `task` tool spawning
   * child sessions) it points at the user-visible ancestor session. The chat
   * UI matches incoming prompts against this so subtask prompts bubble up to
   * the parent session view.
   */
  root_session_id?: string;
  questions: QuestionInfo[];
  tool?: { message_id: string; call_id: string };
}

export interface PermissionRequest {
  id: string;
  session_id: string;
  /** See {@link QuestionRequest.root_session_id}. */
  root_session_id?: string;
  permission: string;
  patterns: string[];
  metadata?: Record<string, unknown>;
  always?: string[];
  tool?: { message_id: string; call_id: string };
}

export interface AgentQuestionEvent {
  type: "agent.question";
  data: QuestionRequest;
}

export interface AgentQuestionResolvedEvent {
  type: "agent.question.resolved";
  data: { request_id: string; session_id: string };
}

export interface AgentPermissionEvent {
  type: "agent.permission";
  data: PermissionRequest;
}

export interface AgentPermissionResolvedEvent {
  type: "agent.permission.resolved";
  data: { request_id: string; session_id: string; reply: string };
}

export interface QueueUpdateEvent {
  type: "queue.update";
  session_id: string;
  data: { event: "enqueued" | "sent" | "error"; messageID: string; error?: string };
}

export interface AgentDiedEvent {
  type: "agent_died";
  workspace_id?: string;
  data: { reason: string };
}

/**
 * Discriminated union of all event types delivered over the workspace SSE stream.
 * Narrow on `type` to access type-specific fields.
 */
export type WorkspaceStreamEvent =
  | WorkspacePhaseEvent
  | SessionStatusEvent
  | AgentEvent
  | AgentQuestionEvent
  | AgentQuestionResolvedEvent
  | AgentPermissionEvent
  | AgentPermissionResolvedEvent
  | QueueUpdateEvent
  | AgentDiedEvent;
