// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later

//go:build tools
// +build tools

// This package contains imports of tools used during the build.
package tools

import (
	// pkg/apis deepcopy + CRD generation: the zz_generated.deepcopy.go
	// files carry controller-gen's header ("Code generated by
	// controller-gen"), and the package is annotated with kubebuilder's
	// object:generate — code-generator's marker-based deepcopy-gen is a
	// silent no-op here (worklog 0870 finding).
	_ "k8s.io/code-generator"
	_ "k8s.io/code-generator/cmd/deepcopy-gen"
	_ "sigs.k8s.io/controller-tools/cmd/controller-gen"
)
