// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later

package abi_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// generatedDirs are the trees that must contain ONLY codegen output. Hand
// edits to generated wire types are how a schema and its implementations
// silently diverge (issue #1135 test plan: no_hand_written_wire). Two gates
// enforce this: (1) this test — every .go file in the generated trees carries
// the protoc codegen marker; (2) `make abi-check` — regenerates in CI and
// fails on any diff, so a hand edit cannot survive regeneration even inside
// a still-marked file.
var generatedDirs = []string{
	"v1",
	"v1/abiconnect",
}

func TestNoHandWrittenWire(t *testing.T) {
	if _, err := os.Stat("v1"); err != nil {
		t.Fatalf("generated package v1 not found (run `make abi-generate`): %v", err)
	}

	seen := 0
	for _, dir := range generatedDirs {
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Fatalf("read %s: %v", dir, err)
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
				continue
			}
			seen++
			path := filepath.Join(dir, e.Name())
			src, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read %s: %v", path, err)
			}
			header := string(src[:min(len(src), 2048)])
			if !strings.Contains(header, "Code generated by protoc-gen") ||
				!strings.Contains(header, "DO NOT EDIT") {
				t.Errorf("%s: hand-written or marker-less file inside the generated surface path", path)
			}
		}
	}
	if seen == 0 {
		t.Fatal("no generated files found — codegen output missing")
	}
}
