// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Typed session actions (design 0055 M1, op 5): one verb slot,
// capability-negotiated. agentd is the sole writer of session mutations;
// actions serialize against delivery via the same per-session single-flight
// machinery. Undeclared actions return NotSupported per the capability
// report — harness differences are data, never API-side branches.

// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file llmsafespaces/abi/v1/action.proto (package llmsafespaces.abi.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ModelRef } from "./contract_pb";
import { file_llmsafespaces_abi_v1_contract } from "./contract_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file llmsafespaces/abi/v1/action.proto.
 */
export const file_llmsafespaces_abi_v1_action: GenFile = /*@__PURE__*/
  fileDesc("CiFsbG1zYWZlc3BhY2VzL2FiaS92MS9hY3Rpb24ucHJvdG8SFGxsbXNhZmVzcGFjZXMuYWJpLnYxIucCCg1BY3Rpb25SZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSOgoJaW50ZXJydXB0GAIgASgLMiUubGxtc2FmZXNwYWNlcy5hYmkudjEuSW50ZXJydXB0QWN0aW9uSAASPwoMc3dpdGNoX21vZGVsGAMgASgLMicubGxtc2FmZXNwYWNlcy5hYmkudjEuU3dpdGNoTW9kZWxBY3Rpb25IABI/Cgxzd2l0Y2hfYWdlbnQYBCABKAsyJy5sbG1zYWZlc3BhY2VzLmFiaS52MS5Td2l0Y2hBZ2VudEFjdGlvbkgAEkIKD2Fuc3dlcl9xdWVzdGlvbhgFIAEoCzInLmxsbXNhZmVzcGFjZXMuYWJpLnYxLkFuc3dlcklucHV0QWN0aW9uSAASNgoHY29tcGFjdBgGIAEoCzIjLmxsbXNhZmVzcGFjZXMuYWJpLnYxLkNvbXBhY3RBY3Rpb25IAEIICgZhY3Rpb24iEQoPSW50ZXJydXB0QWN0aW9uIkIKEVN3aXRjaE1vZGVsQWN0aW9uEi0KBW1vZGVsGAEgASgLMh4ubGxtc2FmZXNwYWNlcy5hYmkudjEuTW9kZWxSZWYiJQoRU3dpdGNoQWdlbnRBY3Rpb24SEAoIYWdlbnRfaWQYASABKAkiYwoRQW5zd2VySW5wdXRBY3Rpb24SEAoIaW5wdXRfaWQYASABKAkSEgoKb3B0aW9uX2lkcxgCIAMoCRIYCgtjdXN0b21fdGV4dBgDIAEoCUgAiAEBQg4KDF9jdXN0b21fdGV4dCIPCg1Db21wYWN0QWN0aW9uIo4DCgxBY3Rpb25SZXN1bHQSEgoKc2Vzc2lvbl9pZBgBIAEoCRI6CglpbnRlcnJ1cHQYAiABKAsyJS5sbG1zYWZlc3BhY2VzLmFiaS52MS5JbnRlcnJ1cHRSZXN1bHRIABI/Cgxzd2l0Y2hfbW9kZWwYAyABKAsyJy5sbG1zYWZlc3BhY2VzLmFiaS52MS5Td2l0Y2hNb2RlbFJlc3VsdEgAEj8KDHN3aXRjaF9hZ2VudBgEIAEoCzInLmxsbXNhZmVzcGFjZXMuYWJpLnYxLlN3aXRjaEFnZW50UmVzdWx0SAASQgoPYW5zd2VyX3F1ZXN0aW9uGAUgASgLMicubGxtc2FmZXNwYWNlcy5hYmkudjEuQW5zd2VySW5wdXRSZXN1bHRIABI2Cgdjb21wYWN0GAYgASgLMiMubGxtc2FmZXNwYWNlcy5hYmkudjEuQ29tcGFjdFJlc3VsdEgAEhcKCmVmZmVjdF9zZXEYByABKARIAYgBAUIICgZyZXN1bHRCDQoLX2VmZmVjdF9zZXEiEQoPSW50ZXJydXB0UmVzdWx0IkIKEVN3aXRjaE1vZGVsUmVzdWx0Ei0KBW1vZGVsGAEgASgLMh4ubGxtc2FmZXNwYWNlcy5hYmkudjEuTW9kZWxSZWYiJQoRU3dpdGNoQWdlbnRSZXN1bHQSEAoIYWdlbnRfaWQYASABKAkiJQoRQW5zd2VySW5wdXRSZXN1bHQSEAoIaW5wdXRfaWQYASABKAkiDwoNQ29tcGFjdFJlc3VsdEIxWi9naXRodWIuY29tL2xlbmF4aWEvbGxtc2FmZXNwYWNlcy9wa2cvYWJpL3YxO2FiaWIGcHJvdG8z", [file_llmsafespaces_abi_v1_contract]);

/**
 * @generated from message llmsafespaces.abi.v1.ActionRequest
 */
export type ActionRequest = Message<"llmsafespaces.abi.v1.ActionRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from oneof llmsafespaces.abi.v1.ActionRequest.action
   */
  action: {
    /**
     * @generated from field: llmsafespaces.abi.v1.InterruptAction interrupt = 2;
     */
    value: InterruptAction;
    case: "interrupt";
  } | {
    /**
     * @generated from field: llmsafespaces.abi.v1.SwitchModelAction switch_model = 3;
     */
    value: SwitchModelAction;
    case: "switchModel";
  } | {
    /**
     * @generated from field: llmsafespaces.abi.v1.SwitchAgentAction switch_agent = 4;
     */
    value: SwitchAgentAction;
    case: "switchAgent";
  } | {
    /**
     * @generated from field: llmsafespaces.abi.v1.AnswerInputAction answer_question = 5;
     */
    value: AnswerInputAction;
    case: "answerQuestion";
  } | {
    /**
     * @generated from field: llmsafespaces.abi.v1.CompactAction compact = 6;
     */
    value: CompactAction;
    case: "compact";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message llmsafespaces.abi.v1.ActionRequest.
 * Use `create(ActionRequestSchema)` to create a new message.
 */
export const ActionRequestSchema: GenMessage<ActionRequest> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 0);

/**
 * InterruptAction aborts the in-flight turn. Non-destructive (I7): it
 * mutates turn projection state only and NEVER entry states — admitted
 * rows survive an interrupt and drain after it.
 *
 * @generated from message llmsafespaces.abi.v1.InterruptAction
 */
export type InterruptAction = Message<"llmsafespaces.abi.v1.InterruptAction"> & {
};

/**
 * Describes the message llmsafespaces.abi.v1.InterruptAction.
 * Use `create(InterruptActionSchema)` to create a new message.
 */
export const InterruptActionSchema: GenMessage<InterruptAction> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 1);

/**
 * @generated from message llmsafespaces.abi.v1.SwitchModelAction
 */
export type SwitchModelAction = Message<"llmsafespaces.abi.v1.SwitchModelAction"> & {
  /**
   * @generated from field: llmsafespaces.abi.v1.ModelRef model = 1;
   */
  model?: ModelRef | undefined;
};

/**
 * Describes the message llmsafespaces.abi.v1.SwitchModelAction.
 * Use `create(SwitchModelActionSchema)` to create a new message.
 */
export const SwitchModelActionSchema: GenMessage<SwitchModelAction> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 2);

/**
 * @generated from message llmsafespaces.abi.v1.SwitchAgentAction
 */
export type SwitchAgentAction = Message<"llmsafespaces.abi.v1.SwitchAgentAction"> & {
  /**
   * @generated from field: string agent_id = 1;
   */
  agentId: string;
};

/**
 * Describes the message llmsafespaces.abi.v1.SwitchAgentAction.
 * Use `create(SwitchAgentActionSchema)` to create a new message.
 */
export const SwitchAgentActionSchema: GenMessage<SwitchAgentAction> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 3);

/**
 * AnswerInputAction answers a pending InputRequest (questions and
 * permissions unified, design 0049 §4.5): selected option labels and/or a
 * custom free-text answer.
 *
 * @generated from message llmsafespaces.abi.v1.AnswerInputAction
 */
export type AnswerInputAction = Message<"llmsafespaces.abi.v1.AnswerInputAction"> & {
  /**
   * @generated from field: string input_id = 1;
   */
  inputId: string;

  /**
   * @generated from field: repeated string option_ids = 2;
   */
  optionIds: string[];

  /**
   * @generated from field: optional string custom_text = 3;
   */
  customText?: string | undefined;
};

/**
 * Describes the message llmsafespaces.abi.v1.AnswerInputAction.
 * Use `create(AnswerInputActionSchema)` to create a new message.
 */
export const AnswerInputActionSchema: GenMessage<AnswerInputAction> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 4);

/**
 * @generated from message llmsafespaces.abi.v1.CompactAction
 */
export type CompactAction = Message<"llmsafespaces.abi.v1.CompactAction"> & {
};

/**
 * Describes the message llmsafespaces.abi.v1.CompactAction.
 * Use `create(CompactActionSchema)` to create a new message.
 */
export const CompactActionSchema: GenMessage<CompactAction> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 5);

/**
 * @generated from message llmsafespaces.abi.v1.ActionResult
 */
export type ActionResult = Message<"llmsafespaces.abi.v1.ActionResult"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from oneof llmsafespaces.abi.v1.ActionResult.result
   */
  result: {
    /**
     * @generated from field: llmsafespaces.abi.v1.InterruptResult interrupt = 2;
     */
    value: InterruptResult;
    case: "interrupt";
  } | {
    /**
     * @generated from field: llmsafespaces.abi.v1.SwitchModelResult switch_model = 3;
     */
    value: SwitchModelResult;
    case: "switchModel";
  } | {
    /**
     * @generated from field: llmsafespaces.abi.v1.SwitchAgentResult switch_agent = 4;
     */
    value: SwitchAgentResult;
    case: "switchAgent";
  } | {
    /**
     * @generated from field: llmsafespaces.abi.v1.AnswerInputResult answer_question = 5;
     */
    value: AnswerInputResult;
    case: "answerQuestion";
  } | {
    /**
     * @generated from field: llmsafespaces.abi.v1.CompactResult compact = 6;
     */
    value: CompactResult;
    case: "compact";
  } | { case: undefined; value?: undefined };

  /**
   * effect_seq is the seq of the event the action produced, when knowable
   * before the response returns (action-result ↔ event causal linkage is a
   * design-0055 open item; unset means "not yet knowable").
   *
   * @generated from field: optional uint64 effect_seq = 7;
   */
  effectSeq?: bigint | undefined;
};

/**
 * Describes the message llmsafespaces.abi.v1.ActionResult.
 * Use `create(ActionResultSchema)` to create a new message.
 */
export const ActionResultSchema: GenMessage<ActionResult> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 6);

/**
 * @generated from message llmsafespaces.abi.v1.InterruptResult
 */
export type InterruptResult = Message<"llmsafespaces.abi.v1.InterruptResult"> & {
};

/**
 * Describes the message llmsafespaces.abi.v1.InterruptResult.
 * Use `create(InterruptResultSchema)` to create a new message.
 */
export const InterruptResultSchema: GenMessage<InterruptResult> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 7);

/**
 * @generated from message llmsafespaces.abi.v1.SwitchModelResult
 */
export type SwitchModelResult = Message<"llmsafespaces.abi.v1.SwitchModelResult"> & {
  /**
   * @generated from field: llmsafespaces.abi.v1.ModelRef model = 1;
   */
  model?: ModelRef | undefined;
};

/**
 * Describes the message llmsafespaces.abi.v1.SwitchModelResult.
 * Use `create(SwitchModelResultSchema)` to create a new message.
 */
export const SwitchModelResultSchema: GenMessage<SwitchModelResult> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 8);

/**
 * @generated from message llmsafespaces.abi.v1.SwitchAgentResult
 */
export type SwitchAgentResult = Message<"llmsafespaces.abi.v1.SwitchAgentResult"> & {
  /**
   * @generated from field: string agent_id = 1;
   */
  agentId: string;
};

/**
 * Describes the message llmsafespaces.abi.v1.SwitchAgentResult.
 * Use `create(SwitchAgentResultSchema)` to create a new message.
 */
export const SwitchAgentResultSchema: GenMessage<SwitchAgentResult> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 9);

/**
 * @generated from message llmsafespaces.abi.v1.AnswerInputResult
 */
export type AnswerInputResult = Message<"llmsafespaces.abi.v1.AnswerInputResult"> & {
  /**
   * @generated from field: string input_id = 1;
   */
  inputId: string;
};

/**
 * Describes the message llmsafespaces.abi.v1.AnswerInputResult.
 * Use `create(AnswerInputResultSchema)` to create a new message.
 */
export const AnswerInputResultSchema: GenMessage<AnswerInputResult> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 10);

/**
 * @generated from message llmsafespaces.abi.v1.CompactResult
 */
export type CompactResult = Message<"llmsafespaces.abi.v1.CompactResult"> & {
};

/**
 * Describes the message llmsafespaces.abi.v1.CompactResult.
 * Use `create(CompactResultSchema)` to create a new message.
 */
export const CompactResultSchema: GenMessage<CompactResult> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_action, 11);

