// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Capability report (design 0055 M1/M4): provenance, supported actions, and
// supported delivery part types ride the events snapshot frame. Harness
// limits are data: every typed action and part kind is declared here, and
// undeclared capability use returns NotSupported — never an API-side branch.

// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file llmsafespaces/abi/v1/capability.proto (package llmsafespaces.abi.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file llmsafespaces/abi/v1/capability.proto.
 */
export const file_llmsafespaces_abi_v1_capability: GenFile = /*@__PURE__*/
  fileDesc("CiVsbG1zYWZlc3BhY2VzL2FiaS92MS9jYXBhYmlsaXR5LnByb3RvEhRsbG1zYWZlc3BhY2VzLmFiaS52MSK7AgoQQ2FwYWJpbGl0eVJlcG9ydBI0Cgpwcm92ZW5hbmNlGAEgASgOMiAubGxtc2FmZXNwYWNlcy5hYmkudjEuUHJvdmVuYW5jZRIPCgdoYXJuZXNzGAIgASgJEhcKD2hhcm5lc3NfdmVyc2lvbhgDIAEoCRIWCg5hZ2VudGRfdmVyc2lvbhgEIAEoCRI7ChFzdXBwb3J0ZWRfYWN0aW9ucxgFIAMoDjIgLmxsbXNhZmVzcGFjZXMuYWJpLnYxLkFjdGlvblR5cGUSSAoYc3VwcG9ydGVkX2RlbGl2ZXJ5X3BhcnRzGAYgAygOMiYubGxtc2FmZXNwYWNlcy5hYmkudjEuRGVsaXZlcnlQYXJ0S2luZBITCgthYmlfdmVyc2lvbhgHIAEoCRITCgt2Ml9kZWxpdmVyeRgIIAEoCCIyCgxOb3RTdXBwb3J0ZWQSEgoKY2FwYWJpbGl0eRgBIAEoCRIOCgZkZXRhaWwYAiABKAkqdQoKUHJvdmVuYW5jZRIaChZQUk9WRU5BTkNFX1VOU1BFQ0lGSUVEEAASHgoaUFJPVkVOQU5DRV9QTEFURk9STV9QSU5ORUQQARIXChNQUk9WRU5BTkNFX1VOUElOTkVEEAISEgoOUFJPVkVOQU5DRV9CWU8QAyq6AQoKQWN0aW9uVHlwZRIbChdBQ1RJT05fVFlQRV9VTlNQRUNJRklFRBAAEhkKFUFDVElPTl9UWVBFX0lOVEVSUlVQVBABEhwKGEFDVElPTl9UWVBFX1NXSVRDSF9NT0RFTBACEhwKGEFDVElPTl9UWVBFX1NXSVRDSF9BR0VOVBADEh8KG0FDVElPTl9UWVBFX0FOU1dFUl9RVUVTVElPThAEEhcKE0FDVElPTl9UWVBFX0NPTVBBQ1QQBSpwChBEZWxpdmVyeVBhcnRLaW5kEiIKHkRFTElWRVJZX1BBUlRfS0lORF9VTlNQRUNJRklFRBAAEhsKF0RFTElWRVJZX1BBUlRfS0lORF9URVhUEAESGwoXREVMSVZFUllfUEFSVF9LSU5EX0ZJTEUQAkIxWi9naXRodWIuY29tL2xlbmF4aWEvbGxtc2FmZXNwYWNlcy9wa2cvYWJpL3YxO2FiaWIGcHJvdG8z");

/**
 * @generated from message llmsafespaces.abi.v1.CapabilityReport
 */
export type CapabilityReport = Message<"llmsafespaces.abi.v1.CapabilityReport"> & {
  /**
   * @generated from field: llmsafespaces.abi.v1.Provenance provenance = 1;
   */
  provenance: Provenance;

  /**
   * @generated from field: string harness = 2;
   */
  harness: string;

  /**
   * @generated from field: string harness_version = 3;
   */
  harnessVersion: string;

  /**
   * @generated from field: string agentd_version = 4;
   */
  agentdVersion: string;

  /**
   * @generated from field: repeated llmsafespaces.abi.v1.ActionType supported_actions = 5;
   */
  supportedActions: ActionType[];

  /**
   * @generated from field: repeated llmsafespaces.abi.v1.DeliveryPartKind supported_delivery_parts = 6;
   */
  supportedDeliveryParts: DeliveryPartKind[];

  /**
   * @generated from field: string abi_version = 7;
   */
  abiVersion: string;

  /**
   * v2_delivery reports whether the harness's V2 session runner surface is
   * present (the M4 flag-matrix "surface present" predicate).
   *
   * @generated from field: bool v2_delivery = 8;
   */
  v2Delivery: boolean;
};

/**
 * Describes the message llmsafespaces.abi.v1.CapabilityReport.
 * Use `create(CapabilityReportSchema)` to create a new message.
 */
export const CapabilityReportSchema: GenMessage<CapabilityReport> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_capability, 0);

/**
 * NotSupported is the typed error detail for capability-gated refusals —
 * undeclared actions and undeclared delivery part kinds. It rides connect
 * CodeUnimplemented errors, so the refusal survives every codec.
 *
 * @generated from message llmsafespaces.abi.v1.NotSupported
 */
export type NotSupported = Message<"llmsafespaces.abi.v1.NotSupported"> & {
  /**
   * @generated from field: string capability = 1;
   */
  capability: string;

  /**
   * @generated from field: string detail = 2;
   */
  detail: string;
};

/**
 * Describes the message llmsafespaces.abi.v1.NotSupported.
 * Use `create(NotSupportedSchema)` to create a new message.
 */
export const NotSupportedSchema: GenMessage<NotSupported> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_capability, 1);

/**
 * Provenance is the 0054 provenance predicate relocated into the report
 * (M4): only PLATFORM_PINNED pods with the state-authority surface may arm
 * AGENTD_STATE_AUTHORITY; the wiring rejects the rest.
 *
 * @generated from enum llmsafespaces.abi.v1.Provenance
 */
export enum Provenance {
  /**
   * @generated from enum value: PROVENANCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PROVENANCE_PLATFORM_PINNED = 1;
   */
  PLATFORM_PINNED = 1,

  /**
   * @generated from enum value: PROVENANCE_UNPINNED = 2;
   */
  UNPINNED = 2,

  /**
   * @generated from enum value: PROVENANCE_BYO = 3;
   */
  BYO = 3,
}

/**
 * Describes the enum llmsafespaces.abi.v1.Provenance.
 */
export const ProvenanceSchema: GenEnum<Provenance> = /*@__PURE__*/
  enumDesc(file_llmsafespaces_abi_v1_capability, 0);

/**
 * ActionType enumerates the op-5 union for capability declaration.
 *
 * @generated from enum llmsafespaces.abi.v1.ActionType
 */
export enum ActionType {
  /**
   * @generated from enum value: ACTION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ACTION_TYPE_INTERRUPT = 1;
   */
  INTERRUPT = 1,

  /**
   * @generated from enum value: ACTION_TYPE_SWITCH_MODEL = 2;
   */
  SWITCH_MODEL = 2,

  /**
   * @generated from enum value: ACTION_TYPE_SWITCH_AGENT = 3;
   */
  SWITCH_AGENT = 3,

  /**
   * @generated from enum value: ACTION_TYPE_ANSWER_QUESTION = 4;
   */
  ANSWER_QUESTION = 4,

  /**
   * @generated from enum value: ACTION_TYPE_COMPACT = 5;
   */
  COMPACT = 5,
}

/**
 * Describes the enum llmsafespaces.abi.v1.ActionType.
 */
export const ActionTypeSchema: GenEnum<ActionType> = /*@__PURE__*/
  enumDesc(file_llmsafespaces_abi_v1_capability, 1);

/**
 * DeliveryPartKind enumerates delivery part kinds for capability
 * declaration. opencode on 1.18.x declares TEXT only (D3).
 *
 * @generated from enum llmsafespaces.abi.v1.DeliveryPartKind
 */
export enum DeliveryPartKind {
  /**
   * @generated from enum value: DELIVERY_PART_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DELIVERY_PART_KIND_TEXT = 1;
   */
  TEXT = 1,

  /**
   * @generated from enum value: DELIVERY_PART_KIND_FILE = 2;
   */
  FILE = 2,
}

/**
 * Describes the enum llmsafespaces.abi.v1.DeliveryPartKind.
 */
export const DeliveryPartKindSchema: GenEnum<DeliveryPartKind> = /*@__PURE__*/
  enumDesc(file_llmsafespaces_abi_v1_capability, 2);

