// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Idempotent in-pod delivery over the agentd ledger (design 0055 M2).
// Dedupe scope is (entry_id, attempt): at-most-once admission per attempt,
// at-least-once effort overall. The delivery POST admits inline (D1-B) —
// 202 from agentd means "durably ledgered" (fsync before ack, I9), never
// "admitted to opencode".

// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file llmsafespaces/abi/v1/delivery.proto (package llmsafespaces.abi.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { ModelRef } from "./contract_pb";
import { file_llmsafespaces_abi_v1_contract } from "./contract_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file llmsafespaces/abi/v1/delivery.proto.
 */
export const file_llmsafespaces_abi_v1_delivery: GenFile = /*@__PURE__*/
  fileDesc("CiNsbG1zYWZlc3BhY2VzL2FiaS92MS9kZWxpdmVyeS5wcm90bxIUbGxtc2FmZXNwYWNlcy5hYmkudjEiKwoNRmlsZVJlZmVyZW5jZRIMCgRwYXRoGAEgASgJEgwKBG5hbWUYAiABKAkiWwoMRGVsaXZlcnlQYXJ0Eg4KBHRleHQYASABKAlIABIzCgRmaWxlGAIgASgLMiMubGxtc2FmZXNwYWNlcy5hYmkudjEuRmlsZVJlZmVyZW5jZUgAQgYKBHBhcnQiuQEKD0RlbGl2ZXJ5UmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEhAKCGVudHJ5X2lkGAIgASgJEg8KB2F0dGVtcHQYAyABKA0SMQoFcGFydHMYBCADKAsyIi5sbG1zYWZlc3BhY2VzLmFiaS52MS5EZWxpdmVyeVBhcnQSMgoFbW9kZWwYBSABKAsyHi5sbG1zYWZlc3BhY2VzLmFiaS52MS5Nb2RlbFJlZkgAiAEBQggKBl9tb2RlbCJiCgtEZWxpdmVyeUFjaxIQCghlbnRyeV9pZBgBIAEoCRIPCgdhdHRlbXB0GAIgASgNEjAKBXN0YXRlGAMgASgOMiEubGxtc2FmZXNwYWNlcy5hYmkudjEuTGVkZ2VyU3RhdGUiUQoYR2V0RGVsaXZlcnlTdGF0dXNSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSEAoIZW50cnlfaWQYAiABKAkSDwoHYXR0ZW1wdBgDIAEoDSLBAQoORGVsaXZlcnlTdGF0dXMSEAoIZW50cnlfaWQYASABKAkSDwoHYXR0ZW1wdBgCIAEoDRIwCgVzdGF0ZRgDIAEoDjIhLmxsbXNhZmVzcGFjZXMuYWJpLnYxLkxlZGdlclN0YXRlEhYKDmZhaWx1cmVfcmVhc29uGAQgASgJEjMKCnVwZGF0ZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSACIAQFCDQoLX3VwZGF0ZWRfYXQqzAEKC0xlZGdlclN0YXRlEhwKGExFREdFUl9TVEFURV9VTlNQRUNJRklFRBAAEhkKFUxFREdFUl9TVEFURV9MRURHRVJFRBABEhkKFUxFREdFUl9TVEFURV9BRE1JVFRFRBACEhkKFUxFREdFUl9TVEFURV9QUk9NT1RFRBADEhsKF0xFREdFUl9TVEFURV9UVVJOX0VOREVEEAQSGAoUTEVER0VSX1NUQVRFX1NUQUxMRUQQBRIXChNMRURHRVJfU1RBVEVfRkFJTEVEEAZCMVovZ2l0aHViLmNvbS9sZW5heGlhL2xsbXNhZmVzcGFjZXMvcGtnL2FiaS92MTthYmliBnByb3RvMw", [file_google_protobuf_timestamp, file_llmsafespaces_abi_v1_contract]);

/**
 * FileReference points at a previously uploaded workspace file (Epic 68
 * upload path shape: /workspace/uploads/<uuid>-<name>).
 *
 * @generated from message llmsafespaces.abi.v1.FileReference
 */
export type FileReference = Message<"llmsafespaces.abi.v1.FileReference"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message llmsafespaces.abi.v1.FileReference.
 * Use `create(FileReferenceSchema)` to create a new message.
 */
export const FileReferenceSchema: GenMessage<FileReference> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_delivery, 0);

/**
 * DeliveryPart is one part of a delivery. The schema is parts-capable from
 * day one (D3); harnesses that only accept text (opencode on 1.18.x) declare
 * file parts NotSupported via the capability report — harness limits are
 * data, not code branches. Multiple text parts are joined in order with
 * newlines into the harness's text field (multi-text-part join rule).
 *
 * @generated from message llmsafespaces.abi.v1.DeliveryPart
 */
export type DeliveryPart = Message<"llmsafespaces.abi.v1.DeliveryPart"> & {
  /**
   * @generated from oneof llmsafespaces.abi.v1.DeliveryPart.part
   */
  part: {
    /**
     * @generated from field: string text = 1;
     */
    value: string;
    case: "text";
  } | {
    /**
     * @generated from field: llmsafespaces.abi.v1.FileReference file = 2;
     */
    value: FileReference;
    case: "file";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message llmsafespaces.abi.v1.DeliveryPart.
 * Use `create(DeliveryPartSchema)` to create a new message.
 */
export const DeliveryPartSchema: GenMessage<DeliveryPart> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_delivery, 1);

/**
 * DeliveryRequest is the outbox's idempotent admission call. entry_id and
 * attempt are outbox-controlled; agentd never invents them.
 *
 * @generated from message llmsafespaces.abi.v1.DeliveryRequest
 */
export type DeliveryRequest = Message<"llmsafespaces.abi.v1.DeliveryRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string entry_id = 2;
   */
  entryId: string;

  /**
   * @generated from field: uint32 attempt = 3;
   */
  attempt: number;

  /**
   * @generated from field: repeated llmsafespaces.abi.v1.DeliveryPart parts = 4;
   */
  parts: DeliveryPart[];

  /**
   * @generated from field: optional llmsafespaces.abi.v1.ModelRef model = 5;
   */
  model?: ModelRef | undefined;
};

/**
 * Describes the message llmsafespaces.abi.v1.DeliveryRequest.
 * Use `create(DeliveryRequestSchema)` to create a new message.
 */
export const DeliveryRequestSchema: GenMessage<DeliveryRequest> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_delivery, 2);

/**
 * DeliveryAck confirms the entry is durably ledgered (I9). state is LEDGERED
 * at ack time; later states are observable via GetDeliveryStatus.
 *
 * @generated from message llmsafespaces.abi.v1.DeliveryAck
 */
export type DeliveryAck = Message<"llmsafespaces.abi.v1.DeliveryAck"> & {
  /**
   * @generated from field: string entry_id = 1;
   */
  entryId: string;

  /**
   * @generated from field: uint32 attempt = 2;
   */
  attempt: number;

  /**
   * @generated from field: llmsafespaces.abi.v1.LedgerState state = 3;
   */
  state: LedgerState;
};

/**
 * Describes the message llmsafespaces.abi.v1.DeliveryAck.
 * Use `create(DeliveryAckSchema)` to create a new message.
 */
export const DeliveryAckSchema: GenMessage<DeliveryAck> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_delivery, 3);

/**
 * @generated from message llmsafespaces.abi.v1.GetDeliveryStatusRequest
 */
export type GetDeliveryStatusRequest = Message<"llmsafespaces.abi.v1.GetDeliveryStatusRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string entry_id = 2;
   */
  entryId: string;

  /**
   * @generated from field: uint32 attempt = 3;
   */
  attempt: number;
};

/**
 * Describes the message llmsafespaces.abi.v1.GetDeliveryStatusRequest.
 * Use `create(GetDeliveryStatusRequestSchema)` to create a new message.
 */
export const GetDeliveryStatusRequestSchema: GenMessage<GetDeliveryStatusRequest> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_delivery, 4);

/**
 * DeliveryStatus is the per-(entry_id, attempt) ledger outcome — the
 * replacement for the API-side text-scan verify oracle.
 *
 * @generated from message llmsafespaces.abi.v1.DeliveryStatus
 */
export type DeliveryStatus = Message<"llmsafespaces.abi.v1.DeliveryStatus"> & {
  /**
   * @generated from field: string entry_id = 1;
   */
  entryId: string;

  /**
   * @generated from field: uint32 attempt = 2;
   */
  attempt: number;

  /**
   * @generated from field: llmsafespaces.abi.v1.LedgerState state = 3;
   */
  state: LedgerState;

  /**
   * @generated from field: string failure_reason = 4;
   */
  failureReason: string;

  /**
   * @generated from field: optional google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message llmsafespaces.abi.v1.DeliveryStatus.
 * Use `create(DeliveryStatusSchema)` to create a new message.
 */
export const DeliveryStatusSchema: GenMessage<DeliveryStatus> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_delivery, 5);

/**
 * LedgerState is the M2 state machine:
 * ledgered → admitted → promoted → turn-ended, with stalled (admitted past
 * the promotion deadline — recovered by wake only, never re-admitted) and
 * failed (per attempt — re-armable as (entry_id, attempt+1)).
 *
 * @generated from enum llmsafespaces.abi.v1.LedgerState
 */
export enum LedgerState {
  /**
   * @generated from enum value: LEDGER_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LEDGER_STATE_LEDGERED = 1;
   */
  LEDGERED = 1,

  /**
   * @generated from enum value: LEDGER_STATE_ADMITTED = 2;
   */
  ADMITTED = 2,

  /**
   * @generated from enum value: LEDGER_STATE_PROMOTED = 3;
   */
  PROMOTED = 3,

  /**
   * @generated from enum value: LEDGER_STATE_TURN_ENDED = 4;
   */
  TURN_ENDED = 4,

  /**
   * @generated from enum value: LEDGER_STATE_STALLED = 5;
   */
  STALLED = 5,

  /**
   * @generated from enum value: LEDGER_STATE_FAILED = 6;
   */
  FAILED = 6,
}

/**
 * Describes the enum llmsafespaces.abi.v1.LedgerState.
 */
export const LedgerStateSchema: GenEnum<LedgerState> = /*@__PURE__*/
  enumDesc(file_llmsafespaces_abi_v1_delivery, 0);

