// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Cursor-typed history (design 0055 §Harness ABI): history is DEFINED in
// the ABI but implemented for opencode only at S5, when upstream ships
// limit/before pagination on its message endpoint. New harnesses are
// ABI-native for history from day one. No RPC exists yet — S5 adds it as an
// additive surface extension; these message shapes freeze with the rest of
// the schema at S2 entrance so the op shape cannot drift in the meantime.

// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file llmsafespaces/abi/v1/history.proto (package llmsafespaces.abi.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message as Message$1 } from "./contract_pb";
import { file_llmsafespaces_abi_v1_contract } from "./contract_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file llmsafespaces/abi/v1/history.proto.
 */
export const file_llmsafespaces_abi_v1_history: GenFile = /*@__PURE__*/
  fileDesc("CiJsbG1zYWZlc3BhY2VzL2FiaS92MS9oaXN0b3J5LnByb3RvEhRsbG1zYWZlc3BhY2VzLmFiaS52MSIYCgZDdXJzb3ISDgoGb3BhcXVlGAEgASgMInEKDkhpc3RvcnlSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSDQoFbGltaXQYAiABKAUSMQoGYmVmb3JlGAMgASgLMhwubGxtc2FmZXNwYWNlcy5hYmkudjEuQ3Vyc29ySACIAQFCCQoHX2JlZm9yZSJ4CgtIaXN0b3J5UGFnZRIvCghtZXNzYWdlcxgBIAMoCzIdLmxsbXNhZmVzcGFjZXMuYWJpLnYxLk1lc3NhZ2USLwoEbmV4dBgCIAEoCzIcLmxsbXNhZmVzcGFjZXMuYWJpLnYxLkN1cnNvckgAiAEBQgcKBV9uZXh0QjFaL2dpdGh1Yi5jb20vbGVuYXhpYS9sbG1zYWZlc3BhY2VzL3BrZy9hYmkvdjE7YWJpYgZwcm90bzM", [file_llmsafespaces_abi_v1_contract]);

/**
 * Cursor is opaque: clients pass it back verbatim and must not interpret it.
 *
 * @generated from message llmsafespaces.abi.v1.Cursor
 */
export type Cursor = Message<"llmsafespaces.abi.v1.Cursor"> & {
  /**
   * @generated from field: bytes opaque = 1;
   */
  opaque: Uint8Array;
};

/**
 * Describes the message llmsafespaces.abi.v1.Cursor.
 * Use `create(CursorSchema)` to create a new message.
 */
export const CursorSchema: GenMessage<Cursor> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_history, 0);

/**
 * @generated from message llmsafespaces.abi.v1.HistoryRequest
 */
export type HistoryRequest = Message<"llmsafespaces.abi.v1.HistoryRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: optional llmsafespaces.abi.v1.Cursor before = 3;
   */
  before?: Cursor | undefined;
};

/**
 * Describes the message llmsafespaces.abi.v1.HistoryRequest.
 * Use `create(HistoryRequestSchema)` to create a new message.
 */
export const HistoryRequestSchema: GenMessage<HistoryRequest> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_history, 1);

/**
 * @generated from message llmsafespaces.abi.v1.HistoryPage
 */
export type HistoryPage = Message<"llmsafespaces.abi.v1.HistoryPage"> & {
  /**
   * @generated from field: repeated llmsafespaces.abi.v1.Message messages = 1;
   */
  messages: Message$1[];

  /**
   * @generated from field: optional llmsafespaces.abi.v1.Cursor next = 2;
   */
  next?: Cursor | undefined;
};

/**
 * Describes the message llmsafespaces.abi.v1.HistoryPage.
 * Use `create(HistoryPageSchema)` to create a new message.
 */
export const HistoryPageSchema: GenMessage<HistoryPage> = /*@__PURE__*/
  messageDesc(file_llmsafespaces_abi_v1_history, 2);

