// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The harness ABI — the entire outward surface of the agentd session-state
// authority (design 0055 M1): five operations in platform schema, frozen.
// If a change wants more than these ops, it belongs in the API.
//
// Sync protocol (M1): connect → snapshot@S → event@S+1 → event@S+2 …
// client rule: apply in order; discard seq ≤ S. There is no replay buffer
// and no since-cursor by design; reconnect mid-turn re-fetches in-flight
// state via a fresh stamped snapshot.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: llmsafespaces/abi/v1/abi.proto

package abi

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReseedReason int32

const (
	ReseedReason_RESEED_REASON_UNSPECIFIED       ReseedReason = 0
	ReseedReason_RESEED_REASON_BOOT              ReseedReason = 1
	ReseedReason_RESEED_REASON_GENERATION_CHANGE ReseedReason = 2
)

// Enum value maps for ReseedReason.
var (
	ReseedReason_name = map[int32]string{
		0: "RESEED_REASON_UNSPECIFIED",
		1: "RESEED_REASON_BOOT",
		2: "RESEED_REASON_GENERATION_CHANGE",
	}
	ReseedReason_value = map[string]int32{
		"RESEED_REASON_UNSPECIFIED":       0,
		"RESEED_REASON_BOOT":              1,
		"RESEED_REASON_GENERATION_CHANGE": 2,
	}
)

func (x ReseedReason) Enum() *ReseedReason {
	p := new(ReseedReason)
	*p = x
	return p
}

func (x ReseedReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReseedReason) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_abi_proto_enumTypes[0].Descriptor()
}

func (ReseedReason) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_abi_proto_enumTypes[0]
}

func (x ReseedReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReseedReason.Descriptor instead.
func (ReseedReason) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_abi_proto_rawDescGZIP(), []int{0}
}

type EventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_abi_proto_rawDescGZIP(), []int{0}
}

// StreamFrame is one item on the events stream.
type StreamFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*StreamFrame_Snapshot
	//	*StreamFrame_Event
	//	*StreamFrame_Reseeded
	Frame         isStreamFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFrame) Reset() {
	*x = StreamFrame{}
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFrame) ProtoMessage() {}

func (x *StreamFrame) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFrame.ProtoReflect.Descriptor instead.
func (*StreamFrame) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_abi_proto_rawDescGZIP(), []int{1}
}

func (x *StreamFrame) GetFrame() isStreamFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *StreamFrame) GetSnapshot() *SnapshotFrame {
	if x != nil {
		if x, ok := x.Frame.(*StreamFrame_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *StreamFrame) GetEvent() *SequencedEvent {
	if x != nil {
		if x, ok := x.Frame.(*StreamFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *StreamFrame) GetReseeded() *ReseedNotice {
	if x != nil {
		if x, ok := x.Frame.(*StreamFrame_Reseeded); ok {
			return x.Reseeded
		}
	}
	return nil
}

type isStreamFrame_Frame interface {
	isStreamFrame_Frame()
}

type StreamFrame_Snapshot struct {
	Snapshot *SnapshotFrame `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type StreamFrame_Event struct {
	Event *SequencedEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type StreamFrame_Reseeded struct {
	Reseeded *ReseedNotice `protobuf:"bytes,3,opt,name=reseeded,proto3,oneof"`
}

func (*StreamFrame_Snapshot) isStreamFrame_Frame() {}

func (*StreamFrame_Event) isStreamFrame_Frame() {}

func (*StreamFrame_Reseeded) isStreamFrame_Frame() {}

// SnapshotFrame is always the first frame on a connection. at_seq is the
// atomic stamp: the snapshot is exactly the fold of events 1..at_seq
// captured under the projection lock (I1/I2).
type SnapshotFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtSeq         uint64                 `protobuf:"varint,1,opt,name=at_seq,json=atSeq,proto3" json:"at_seq,omitempty"`
	Snapshot      *PodSnapshot           `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Capabilities  *CapabilityReport      `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotFrame) Reset() {
	*x = SnapshotFrame{}
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotFrame) ProtoMessage() {}

func (x *SnapshotFrame) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotFrame.ProtoReflect.Descriptor instead.
func (*SnapshotFrame) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_abi_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotFrame) GetAtSeq() uint64 {
	if x != nil {
		return x.AtSeq
	}
	return 0
}

func (x *SnapshotFrame) GetSnapshot() *PodSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *SnapshotFrame) GetCapabilities() *CapabilityReport {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// PodSnapshot is the pod-wide in-flight state. Sessions with no in-flight
// state may be omitted; the set is capped (S1 spike: snapshot size at N
// sessions).
type PodSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionSnapshot     `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodSnapshot) Reset() {
	*x = PodSnapshot{}
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodSnapshot) ProtoMessage() {}

func (x *PodSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodSnapshot.ProtoReflect.Descriptor instead.
func (*PodSnapshot) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_abi_proto_rawDescGZIP(), []int{3}
}

func (x *PodSnapshot) GetSessions() []*SessionSnapshot {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// SequencedEvent carries one contract event stamped with the pod-local
// monotonic seq assigned by agentd.
type SequencedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequencedEvent) Reset() {
	*x = SequencedEvent{}
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequencedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencedEvent) ProtoMessage() {}

func (x *SequencedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencedEvent.ProtoReflect.Descriptor instead.
func (*SequencedEvent) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_abi_proto_rawDescGZIP(), []int{4}
}

func (x *SequencedEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SequencedEvent) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// ReseedNotice is the synthetic invalidation signal (I3): the projection
// was reseeded from the harness store; live clients MUST re-snapshot. It
// consumes the next seq so ordering stays monotonic across the rebuild.
type ReseedNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Reason        ReseedReason           `protobuf:"varint,2,opt,name=reason,proto3,enum=llmsafespaces.abi.v1.ReseedReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReseedNotice) Reset() {
	*x = ReseedNotice{}
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReseedNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReseedNotice) ProtoMessage() {}

func (x *ReseedNotice) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReseedNotice.ProtoReflect.Descriptor instead.
func (*ReseedNotice) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_abi_proto_rawDescGZIP(), []int{5}
}

func (x *ReseedNotice) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ReseedNotice) GetReason() ReseedReason {
	if x != nil {
		return x.Reason
	}
	return ReseedReason_RESEED_REASON_UNSPECIFIED
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_abi_proto_rawDescGZIP(), []int{6}
}

func (x *GetSnapshotRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// SessionSnapshot is one session's authoritative state (I12).
type SessionSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=llmsafespaces.abi.v1.SessionStatus" json:"status,omitempty"`
	InFlightParts []*Part                `protobuf:"bytes,3,rep,name=in_flight_parts,json=inFlightParts,proto3" json:"in_flight_parts,omitempty"`
	QueueDepth    int32                  `protobuf:"varint,4,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	PendingInputs []*InputRequest        `protobuf:"bytes,5,rep,name=pending_inputs,json=pendingInputs,proto3" json:"pending_inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSnapshot) Reset() {
	*x = SessionSnapshot{}
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSnapshot) ProtoMessage() {}

func (x *SessionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_abi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSnapshot.ProtoReflect.Descriptor instead.
func (*SessionSnapshot) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_abi_proto_rawDescGZIP(), []int{7}
}

func (x *SessionSnapshot) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSnapshot) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *SessionSnapshot) GetInFlightParts() []*Part {
	if x != nil {
		return x.InFlightParts
	}
	return nil
}

func (x *SessionSnapshot) GetQueueDepth() int32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *SessionSnapshot) GetPendingInputs() []*InputRequest {
	if x != nil {
		return x.PendingInputs
	}
	return nil
}

var File_llmsafespaces_abi_v1_abi_proto protoreflect.FileDescriptor

const file_llmsafespaces_abi_v1_abi_proto_rawDesc = "" +
	"\n" +
	"\x1ellmsafespaces/abi/v1/abi.proto\x12\x14llmsafespaces.abi.v1\x1a!llmsafespaces/abi/v1/action.proto\x1a%llmsafespaces/abi/v1/capability.proto\x1a#llmsafespaces/abi/v1/contract.proto\x1a#llmsafespaces/abi/v1/delivery.proto\"\x0f\n" +
	"\rEventsRequest\"\xd9\x01\n" +
	"\vStreamFrame\x12A\n" +
	"\bsnapshot\x18\x01 \x01(\v2#.llmsafespaces.abi.v1.SnapshotFrameH\x00R\bsnapshot\x12<\n" +
	"\x05event\x18\x02 \x01(\v2$.llmsafespaces.abi.v1.SequencedEventH\x00R\x05event\x12@\n" +
	"\breseeded\x18\x03 \x01(\v2\".llmsafespaces.abi.v1.ReseedNoticeH\x00R\breseededB\a\n" +
	"\x05frame\"\xb1\x01\n" +
	"\rSnapshotFrame\x12\x15\n" +
	"\x06at_seq\x18\x01 \x01(\x04R\x05atSeq\x12=\n" +
	"\bsnapshot\x18\x02 \x01(\v2!.llmsafespaces.abi.v1.PodSnapshotR\bsnapshot\x12J\n" +
	"\fcapabilities\x18\x03 \x01(\v2&.llmsafespaces.abi.v1.CapabilityReportR\fcapabilities\"P\n" +
	"\vPodSnapshot\x12A\n" +
	"\bsessions\x18\x01 \x03(\v2%.llmsafespaces.abi.v1.SessionSnapshotR\bsessions\"U\n" +
	"\x0eSequencedEvent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x121\n" +
	"\x05event\x18\x02 \x01(\v2\x1b.llmsafespaces.abi.v1.EventR\x05event\"\\\n" +
	"\fReseedNotice\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12:\n" +
	"\x06reason\x18\x02 \x01(\x0e2\".llmsafespaces.abi.v1.ReseedReasonR\x06reason\"3\n" +
	"\x12GetSnapshotRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x9d\x02\n" +
	"\x0fSessionSnapshot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.llmsafespaces.abi.v1.SessionStatusR\x06status\x12B\n" +
	"\x0fin_flight_parts\x18\x03 \x03(\v2\x1a.llmsafespaces.abi.v1.PartR\rinFlightParts\x12\x1f\n" +
	"\vqueue_depth\x18\x04 \x01(\x05R\n" +
	"queueDepth\x12I\n" +
	"\x0epending_inputs\x18\x05 \x03(\v2\".llmsafespaces.abi.v1.InputRequestR\rpendingInputs*j\n" +
	"\fReseedReason\x12\x1d\n" +
	"\x19RESEED_REASON_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RESEED_REASON_BOOT\x10\x01\x12#\n" +
	"\x1fRESEED_REASON_GENERATION_CHANGE\x10\x022\xd7\x03\n" +
	"\x11HarnessABIService\x12R\n" +
	"\x06Events\x12#.llmsafespaces.abi.v1.EventsRequest\x1a!.llmsafespaces.abi.v1.StreamFrame0\x01\x12^\n" +
	"\vGetSnapshot\x12(.llmsafespaces.abi.v1.GetSnapshotRequest\x1a%.llmsafespaces.abi.v1.SessionSnapshot\x12S\n" +
	"\aDeliver\x12%.llmsafespaces.abi.v1.DeliveryRequest\x1a!.llmsafespaces.abi.v1.DeliveryAck\x12i\n" +
	"\x11GetDeliveryStatus\x12..llmsafespaces.abi.v1.GetDeliveryStatusRequest\x1a$.llmsafespaces.abi.v1.DeliveryStatus\x12N\n" +
	"\x03Act\x12#.llmsafespaces.abi.v1.ActionRequest\x1a\".llmsafespaces.abi.v1.ActionResultB1Z/github.com/lenaxia/llmsafespaces/pkg/abi/v1;abib\x06proto3"

var (
	file_llmsafespaces_abi_v1_abi_proto_rawDescOnce sync.Once
	file_llmsafespaces_abi_v1_abi_proto_rawDescData []byte
)

func file_llmsafespaces_abi_v1_abi_proto_rawDescGZIP() []byte {
	file_llmsafespaces_abi_v1_abi_proto_rawDescOnce.Do(func() {
		file_llmsafespaces_abi_v1_abi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_abi_proto_rawDesc), len(file_llmsafespaces_abi_v1_abi_proto_rawDesc)))
	})
	return file_llmsafespaces_abi_v1_abi_proto_rawDescData
}

var file_llmsafespaces_abi_v1_abi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_llmsafespaces_abi_v1_abi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_llmsafespaces_abi_v1_abi_proto_goTypes = []any{
	(ReseedReason)(0),                // 0: llmsafespaces.abi.v1.ReseedReason
	(*EventsRequest)(nil),            // 1: llmsafespaces.abi.v1.EventsRequest
	(*StreamFrame)(nil),              // 2: llmsafespaces.abi.v1.StreamFrame
	(*SnapshotFrame)(nil),            // 3: llmsafespaces.abi.v1.SnapshotFrame
	(*PodSnapshot)(nil),              // 4: llmsafespaces.abi.v1.PodSnapshot
	(*SequencedEvent)(nil),           // 5: llmsafespaces.abi.v1.SequencedEvent
	(*ReseedNotice)(nil),             // 6: llmsafespaces.abi.v1.ReseedNotice
	(*GetSnapshotRequest)(nil),       // 7: llmsafespaces.abi.v1.GetSnapshotRequest
	(*SessionSnapshot)(nil),          // 8: llmsafespaces.abi.v1.SessionSnapshot
	(*CapabilityReport)(nil),         // 9: llmsafespaces.abi.v1.CapabilityReport
	(*Event)(nil),                    // 10: llmsafespaces.abi.v1.Event
	(SessionStatus)(0),               // 11: llmsafespaces.abi.v1.SessionStatus
	(*Part)(nil),                     // 12: llmsafespaces.abi.v1.Part
	(*InputRequest)(nil),             // 13: llmsafespaces.abi.v1.InputRequest
	(*DeliveryRequest)(nil),          // 14: llmsafespaces.abi.v1.DeliveryRequest
	(*GetDeliveryStatusRequest)(nil), // 15: llmsafespaces.abi.v1.GetDeliveryStatusRequest
	(*ActionRequest)(nil),            // 16: llmsafespaces.abi.v1.ActionRequest
	(*DeliveryAck)(nil),              // 17: llmsafespaces.abi.v1.DeliveryAck
	(*DeliveryStatus)(nil),           // 18: llmsafespaces.abi.v1.DeliveryStatus
	(*ActionResult)(nil),             // 19: llmsafespaces.abi.v1.ActionResult
}
var file_llmsafespaces_abi_v1_abi_proto_depIdxs = []int32{
	3,  // 0: llmsafespaces.abi.v1.StreamFrame.snapshot:type_name -> llmsafespaces.abi.v1.SnapshotFrame
	5,  // 1: llmsafespaces.abi.v1.StreamFrame.event:type_name -> llmsafespaces.abi.v1.SequencedEvent
	6,  // 2: llmsafespaces.abi.v1.StreamFrame.reseeded:type_name -> llmsafespaces.abi.v1.ReseedNotice
	4,  // 3: llmsafespaces.abi.v1.SnapshotFrame.snapshot:type_name -> llmsafespaces.abi.v1.PodSnapshot
	9,  // 4: llmsafespaces.abi.v1.SnapshotFrame.capabilities:type_name -> llmsafespaces.abi.v1.CapabilityReport
	8,  // 5: llmsafespaces.abi.v1.PodSnapshot.sessions:type_name -> llmsafespaces.abi.v1.SessionSnapshot
	10, // 6: llmsafespaces.abi.v1.SequencedEvent.event:type_name -> llmsafespaces.abi.v1.Event
	0,  // 7: llmsafespaces.abi.v1.ReseedNotice.reason:type_name -> llmsafespaces.abi.v1.ReseedReason
	11, // 8: llmsafespaces.abi.v1.SessionSnapshot.status:type_name -> llmsafespaces.abi.v1.SessionStatus
	12, // 9: llmsafespaces.abi.v1.SessionSnapshot.in_flight_parts:type_name -> llmsafespaces.abi.v1.Part
	13, // 10: llmsafespaces.abi.v1.SessionSnapshot.pending_inputs:type_name -> llmsafespaces.abi.v1.InputRequest
	1,  // 11: llmsafespaces.abi.v1.HarnessABIService.Events:input_type -> llmsafespaces.abi.v1.EventsRequest
	7,  // 12: llmsafespaces.abi.v1.HarnessABIService.GetSnapshot:input_type -> llmsafespaces.abi.v1.GetSnapshotRequest
	14, // 13: llmsafespaces.abi.v1.HarnessABIService.Deliver:input_type -> llmsafespaces.abi.v1.DeliveryRequest
	15, // 14: llmsafespaces.abi.v1.HarnessABIService.GetDeliveryStatus:input_type -> llmsafespaces.abi.v1.GetDeliveryStatusRequest
	16, // 15: llmsafespaces.abi.v1.HarnessABIService.Act:input_type -> llmsafespaces.abi.v1.ActionRequest
	2,  // 16: llmsafespaces.abi.v1.HarnessABIService.Events:output_type -> llmsafespaces.abi.v1.StreamFrame
	8,  // 17: llmsafespaces.abi.v1.HarnessABIService.GetSnapshot:output_type -> llmsafespaces.abi.v1.SessionSnapshot
	17, // 18: llmsafespaces.abi.v1.HarnessABIService.Deliver:output_type -> llmsafespaces.abi.v1.DeliveryAck
	18, // 19: llmsafespaces.abi.v1.HarnessABIService.GetDeliveryStatus:output_type -> llmsafespaces.abi.v1.DeliveryStatus
	19, // 20: llmsafespaces.abi.v1.HarnessABIService.Act:output_type -> llmsafespaces.abi.v1.ActionResult
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_llmsafespaces_abi_v1_abi_proto_init() }
func file_llmsafespaces_abi_v1_abi_proto_init() {
	if File_llmsafespaces_abi_v1_abi_proto != nil {
		return
	}
	file_llmsafespaces_abi_v1_action_proto_init()
	file_llmsafespaces_abi_v1_capability_proto_init()
	file_llmsafespaces_abi_v1_contract_proto_init()
	file_llmsafespaces_abi_v1_delivery_proto_init()
	file_llmsafespaces_abi_v1_abi_proto_msgTypes[1].OneofWrappers = []any{
		(*StreamFrame_Snapshot)(nil),
		(*StreamFrame_Event)(nil),
		(*StreamFrame_Reseeded)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_abi_proto_rawDesc), len(file_llmsafespaces_abi_v1_abi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llmsafespaces_abi_v1_abi_proto_goTypes,
		DependencyIndexes: file_llmsafespaces_abi_v1_abi_proto_depIdxs,
		EnumInfos:         file_llmsafespaces_abi_v1_abi_proto_enumTypes,
		MessageInfos:      file_llmsafespaces_abi_v1_abi_proto_msgTypes,
	}.Build()
	File_llmsafespaces_abi_v1_abi_proto = out.File
	file_llmsafespaces_abi_v1_abi_proto_goTypes = nil
	file_llmsafespaces_abi_v1_abi_proto_depIdxs = nil
}
