// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Typed session actions (design 0055 M1, op 5): one verb slot,
// capability-negotiated. agentd is the sole writer of session mutations;
// actions serialize against delivery via the same per-session single-flight
// machinery. Undeclared actions return NotSupported per the capability
// report — harness differences are data, never API-side branches.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: llmsafespaces/abi/v1/action.proto

package abi

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*ActionRequest_Interrupt
	//	*ActionRequest_SwitchModel
	//	*ActionRequest_SwitchAgent
	//	*ActionRequest_AnswerQuestion
	//	*ActionRequest_Compact
	Action        isActionRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{0}
}

func (x *ActionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ActionRequest) GetAction() isActionRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ActionRequest) GetInterrupt() *InterruptAction {
	if x != nil {
		if x, ok := x.Action.(*ActionRequest_Interrupt); ok {
			return x.Interrupt
		}
	}
	return nil
}

func (x *ActionRequest) GetSwitchModel() *SwitchModelAction {
	if x != nil {
		if x, ok := x.Action.(*ActionRequest_SwitchModel); ok {
			return x.SwitchModel
		}
	}
	return nil
}

func (x *ActionRequest) GetSwitchAgent() *SwitchAgentAction {
	if x != nil {
		if x, ok := x.Action.(*ActionRequest_SwitchAgent); ok {
			return x.SwitchAgent
		}
	}
	return nil
}

func (x *ActionRequest) GetAnswerQuestion() *AnswerInputAction {
	if x != nil {
		if x, ok := x.Action.(*ActionRequest_AnswerQuestion); ok {
			return x.AnswerQuestion
		}
	}
	return nil
}

func (x *ActionRequest) GetCompact() *CompactAction {
	if x != nil {
		if x, ok := x.Action.(*ActionRequest_Compact); ok {
			return x.Compact
		}
	}
	return nil
}

type isActionRequest_Action interface {
	isActionRequest_Action()
}

type ActionRequest_Interrupt struct {
	Interrupt *InterruptAction `protobuf:"bytes,2,opt,name=interrupt,proto3,oneof"`
}

type ActionRequest_SwitchModel struct {
	SwitchModel *SwitchModelAction `protobuf:"bytes,3,opt,name=switch_model,json=switchModel,proto3,oneof"`
}

type ActionRequest_SwitchAgent struct {
	SwitchAgent *SwitchAgentAction `protobuf:"bytes,4,opt,name=switch_agent,json=switchAgent,proto3,oneof"`
}

type ActionRequest_AnswerQuestion struct {
	AnswerQuestion *AnswerInputAction `protobuf:"bytes,5,opt,name=answer_question,json=answerQuestion,proto3,oneof"`
}

type ActionRequest_Compact struct {
	Compact *CompactAction `protobuf:"bytes,6,opt,name=compact,proto3,oneof"`
}

func (*ActionRequest_Interrupt) isActionRequest_Action() {}

func (*ActionRequest_SwitchModel) isActionRequest_Action() {}

func (*ActionRequest_SwitchAgent) isActionRequest_Action() {}

func (*ActionRequest_AnswerQuestion) isActionRequest_Action() {}

func (*ActionRequest_Compact) isActionRequest_Action() {}

// InterruptAction aborts the in-flight turn. Non-destructive (I7): it
// mutates turn projection state only and NEVER entry states — admitted
// rows survive an interrupt and drain after it.
type InterruptAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptAction) Reset() {
	*x = InterruptAction{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptAction) ProtoMessage() {}

func (x *InterruptAction) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptAction.ProtoReflect.Descriptor instead.
func (*InterruptAction) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{1}
}

type SwitchModelAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ModelRef              `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchModelAction) Reset() {
	*x = SwitchModelAction{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchModelAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchModelAction) ProtoMessage() {}

func (x *SwitchModelAction) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchModelAction.ProtoReflect.Descriptor instead.
func (*SwitchModelAction) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{2}
}

func (x *SwitchModelAction) GetModel() *ModelRef {
	if x != nil {
		return x.Model
	}
	return nil
}

type SwitchAgentAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchAgentAction) Reset() {
	*x = SwitchAgentAction{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchAgentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchAgentAction) ProtoMessage() {}

func (x *SwitchAgentAction) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchAgentAction.ProtoReflect.Descriptor instead.
func (*SwitchAgentAction) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{3}
}

func (x *SwitchAgentAction) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// AnswerInputAction answers a pending InputRequest (questions and
// permissions unified, design 0049 §4.5): selected option labels and/or a
// custom free-text answer.
type AnswerInputAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputId       string                 `protobuf:"bytes,1,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	OptionIds     []string               `protobuf:"bytes,2,rep,name=option_ids,json=optionIds,proto3" json:"option_ids,omitempty"`
	CustomText    *string                `protobuf:"bytes,3,opt,name=custom_text,json=customText,proto3,oneof" json:"custom_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerInputAction) Reset() {
	*x = AnswerInputAction{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerInputAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerInputAction) ProtoMessage() {}

func (x *AnswerInputAction) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerInputAction.ProtoReflect.Descriptor instead.
func (*AnswerInputAction) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{4}
}

func (x *AnswerInputAction) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *AnswerInputAction) GetOptionIds() []string {
	if x != nil {
		return x.OptionIds
	}
	return nil
}

func (x *AnswerInputAction) GetCustomText() string {
	if x != nil && x.CustomText != nil {
		return *x.CustomText
	}
	return ""
}

type CompactAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactAction) Reset() {
	*x = CompactAction{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactAction) ProtoMessage() {}

func (x *CompactAction) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactAction.ProtoReflect.Descriptor instead.
func (*CompactAction) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{5}
}

type ActionResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ActionResult_Interrupt
	//	*ActionResult_SwitchModel
	//	*ActionResult_SwitchAgent
	//	*ActionResult_AnswerQuestion
	//	*ActionResult_Compact
	Result isActionResult_Result `protobuf_oneof:"result"`
	// effect_seq is the seq of the event the action produced, when knowable
	// before the response returns (action-result ↔ event causal linkage is a
	// design-0055 open item; unset means "not yet knowable").
	EffectSeq     *uint64 `protobuf:"varint,7,opt,name=effect_seq,json=effectSeq,proto3,oneof" json:"effect_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{6}
}

func (x *ActionResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ActionResult) GetResult() isActionResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ActionResult) GetInterrupt() *InterruptResult {
	if x != nil {
		if x, ok := x.Result.(*ActionResult_Interrupt); ok {
			return x.Interrupt
		}
	}
	return nil
}

func (x *ActionResult) GetSwitchModel() *SwitchModelResult {
	if x != nil {
		if x, ok := x.Result.(*ActionResult_SwitchModel); ok {
			return x.SwitchModel
		}
	}
	return nil
}

func (x *ActionResult) GetSwitchAgent() *SwitchAgentResult {
	if x != nil {
		if x, ok := x.Result.(*ActionResult_SwitchAgent); ok {
			return x.SwitchAgent
		}
	}
	return nil
}

func (x *ActionResult) GetAnswerQuestion() *AnswerInputResult {
	if x != nil {
		if x, ok := x.Result.(*ActionResult_AnswerQuestion); ok {
			return x.AnswerQuestion
		}
	}
	return nil
}

func (x *ActionResult) GetCompact() *CompactResult {
	if x != nil {
		if x, ok := x.Result.(*ActionResult_Compact); ok {
			return x.Compact
		}
	}
	return nil
}

func (x *ActionResult) GetEffectSeq() uint64 {
	if x != nil && x.EffectSeq != nil {
		return *x.EffectSeq
	}
	return 0
}

type isActionResult_Result interface {
	isActionResult_Result()
}

type ActionResult_Interrupt struct {
	Interrupt *InterruptResult `protobuf:"bytes,2,opt,name=interrupt,proto3,oneof"`
}

type ActionResult_SwitchModel struct {
	SwitchModel *SwitchModelResult `protobuf:"bytes,3,opt,name=switch_model,json=switchModel,proto3,oneof"`
}

type ActionResult_SwitchAgent struct {
	SwitchAgent *SwitchAgentResult `protobuf:"bytes,4,opt,name=switch_agent,json=switchAgent,proto3,oneof"`
}

type ActionResult_AnswerQuestion struct {
	AnswerQuestion *AnswerInputResult `protobuf:"bytes,5,opt,name=answer_question,json=answerQuestion,proto3,oneof"`
}

type ActionResult_Compact struct {
	Compact *CompactResult `protobuf:"bytes,6,opt,name=compact,proto3,oneof"`
}

func (*ActionResult_Interrupt) isActionResult_Result() {}

func (*ActionResult_SwitchModel) isActionResult_Result() {}

func (*ActionResult_SwitchAgent) isActionResult_Result() {}

func (*ActionResult_AnswerQuestion) isActionResult_Result() {}

func (*ActionResult_Compact) isActionResult_Result() {}

type InterruptResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptResult) Reset() {
	*x = InterruptResult{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptResult) ProtoMessage() {}

func (x *InterruptResult) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptResult.ProtoReflect.Descriptor instead.
func (*InterruptResult) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{7}
}

type SwitchModelResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ModelRef              `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchModelResult) Reset() {
	*x = SwitchModelResult{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchModelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchModelResult) ProtoMessage() {}

func (x *SwitchModelResult) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchModelResult.ProtoReflect.Descriptor instead.
func (*SwitchModelResult) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{8}
}

func (x *SwitchModelResult) GetModel() *ModelRef {
	if x != nil {
		return x.Model
	}
	return nil
}

type SwitchAgentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchAgentResult) Reset() {
	*x = SwitchAgentResult{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchAgentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchAgentResult) ProtoMessage() {}

func (x *SwitchAgentResult) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchAgentResult.ProtoReflect.Descriptor instead.
func (*SwitchAgentResult) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{9}
}

func (x *SwitchAgentResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AnswerInputResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputId       string                 `protobuf:"bytes,1,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerInputResult) Reset() {
	*x = AnswerInputResult{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerInputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerInputResult) ProtoMessage() {}

func (x *AnswerInputResult) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerInputResult.ProtoReflect.Descriptor instead.
func (*AnswerInputResult) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{10}
}

func (x *AnswerInputResult) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

type CompactResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactResult) Reset() {
	*x = CompactResult{}
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResult) ProtoMessage() {}

func (x *CompactResult) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_action_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResult.ProtoReflect.Descriptor instead.
func (*CompactResult) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_action_proto_rawDescGZIP(), []int{11}
}

var File_llmsafespaces_abi_v1_action_proto protoreflect.FileDescriptor

const file_llmsafespaces_abi_v1_action_proto_rawDesc = "" +
	"\n" +
	"!llmsafespaces/abi/v1/action.proto\x12\x14llmsafespaces.abi.v1\x1a#llmsafespaces/abi/v1/contract.proto\"\xb0\x03\n" +
	"\rActionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12E\n" +
	"\tinterrupt\x18\x02 \x01(\v2%.llmsafespaces.abi.v1.InterruptActionH\x00R\tinterrupt\x12L\n" +
	"\fswitch_model\x18\x03 \x01(\v2'.llmsafespaces.abi.v1.SwitchModelActionH\x00R\vswitchModel\x12L\n" +
	"\fswitch_agent\x18\x04 \x01(\v2'.llmsafespaces.abi.v1.SwitchAgentActionH\x00R\vswitchAgent\x12R\n" +
	"\x0fanswer_question\x18\x05 \x01(\v2'.llmsafespaces.abi.v1.AnswerInputActionH\x00R\x0eanswerQuestion\x12?\n" +
	"\acompact\x18\x06 \x01(\v2#.llmsafespaces.abi.v1.CompactActionH\x00R\acompactB\b\n" +
	"\x06action\"\x11\n" +
	"\x0fInterruptAction\"I\n" +
	"\x11SwitchModelAction\x124\n" +
	"\x05model\x18\x01 \x01(\v2\x1e.llmsafespaces.abi.v1.ModelRefR\x05model\".\n" +
	"\x11SwitchAgentAction\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x83\x01\n" +
	"\x11AnswerInputAction\x12\x19\n" +
	"\binput_id\x18\x01 \x01(\tR\ainputId\x12\x1d\n" +
	"\n" +
	"option_ids\x18\x02 \x03(\tR\toptionIds\x12$\n" +
	"\vcustom_text\x18\x03 \x01(\tH\x00R\n" +
	"customText\x88\x01\x01B\x0e\n" +
	"\f_custom_text\"\x0f\n" +
	"\rCompactAction\"\xe2\x03\n" +
	"\fActionResult\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12E\n" +
	"\tinterrupt\x18\x02 \x01(\v2%.llmsafespaces.abi.v1.InterruptResultH\x00R\tinterrupt\x12L\n" +
	"\fswitch_model\x18\x03 \x01(\v2'.llmsafespaces.abi.v1.SwitchModelResultH\x00R\vswitchModel\x12L\n" +
	"\fswitch_agent\x18\x04 \x01(\v2'.llmsafespaces.abi.v1.SwitchAgentResultH\x00R\vswitchAgent\x12R\n" +
	"\x0fanswer_question\x18\x05 \x01(\v2'.llmsafespaces.abi.v1.AnswerInputResultH\x00R\x0eanswerQuestion\x12?\n" +
	"\acompact\x18\x06 \x01(\v2#.llmsafespaces.abi.v1.CompactResultH\x00R\acompact\x12\"\n" +
	"\n" +
	"effect_seq\x18\a \x01(\x04H\x01R\teffectSeq\x88\x01\x01B\b\n" +
	"\x06resultB\r\n" +
	"\v_effect_seq\"\x11\n" +
	"\x0fInterruptResult\"I\n" +
	"\x11SwitchModelResult\x124\n" +
	"\x05model\x18\x01 \x01(\v2\x1e.llmsafespaces.abi.v1.ModelRefR\x05model\".\n" +
	"\x11SwitchAgentResult\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\".\n" +
	"\x11AnswerInputResult\x12\x19\n" +
	"\binput_id\x18\x01 \x01(\tR\ainputId\"\x0f\n" +
	"\rCompactResultB1Z/github.com/lenaxia/llmsafespaces/pkg/abi/v1;abib\x06proto3"

var (
	file_llmsafespaces_abi_v1_action_proto_rawDescOnce sync.Once
	file_llmsafespaces_abi_v1_action_proto_rawDescData []byte
)

func file_llmsafespaces_abi_v1_action_proto_rawDescGZIP() []byte {
	file_llmsafespaces_abi_v1_action_proto_rawDescOnce.Do(func() {
		file_llmsafespaces_abi_v1_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_action_proto_rawDesc), len(file_llmsafespaces_abi_v1_action_proto_rawDesc)))
	})
	return file_llmsafespaces_abi_v1_action_proto_rawDescData
}

var file_llmsafespaces_abi_v1_action_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_llmsafespaces_abi_v1_action_proto_goTypes = []any{
	(*ActionRequest)(nil),     // 0: llmsafespaces.abi.v1.ActionRequest
	(*InterruptAction)(nil),   // 1: llmsafespaces.abi.v1.InterruptAction
	(*SwitchModelAction)(nil), // 2: llmsafespaces.abi.v1.SwitchModelAction
	(*SwitchAgentAction)(nil), // 3: llmsafespaces.abi.v1.SwitchAgentAction
	(*AnswerInputAction)(nil), // 4: llmsafespaces.abi.v1.AnswerInputAction
	(*CompactAction)(nil),     // 5: llmsafespaces.abi.v1.CompactAction
	(*ActionResult)(nil),      // 6: llmsafespaces.abi.v1.ActionResult
	(*InterruptResult)(nil),   // 7: llmsafespaces.abi.v1.InterruptResult
	(*SwitchModelResult)(nil), // 8: llmsafespaces.abi.v1.SwitchModelResult
	(*SwitchAgentResult)(nil), // 9: llmsafespaces.abi.v1.SwitchAgentResult
	(*AnswerInputResult)(nil), // 10: llmsafespaces.abi.v1.AnswerInputResult
	(*CompactResult)(nil),     // 11: llmsafespaces.abi.v1.CompactResult
	(*ModelRef)(nil),          // 12: llmsafespaces.abi.v1.ModelRef
}
var file_llmsafespaces_abi_v1_action_proto_depIdxs = []int32{
	1,  // 0: llmsafespaces.abi.v1.ActionRequest.interrupt:type_name -> llmsafespaces.abi.v1.InterruptAction
	2,  // 1: llmsafespaces.abi.v1.ActionRequest.switch_model:type_name -> llmsafespaces.abi.v1.SwitchModelAction
	3,  // 2: llmsafespaces.abi.v1.ActionRequest.switch_agent:type_name -> llmsafespaces.abi.v1.SwitchAgentAction
	4,  // 3: llmsafespaces.abi.v1.ActionRequest.answer_question:type_name -> llmsafespaces.abi.v1.AnswerInputAction
	5,  // 4: llmsafespaces.abi.v1.ActionRequest.compact:type_name -> llmsafespaces.abi.v1.CompactAction
	12, // 5: llmsafespaces.abi.v1.SwitchModelAction.model:type_name -> llmsafespaces.abi.v1.ModelRef
	7,  // 6: llmsafespaces.abi.v1.ActionResult.interrupt:type_name -> llmsafespaces.abi.v1.InterruptResult
	8,  // 7: llmsafespaces.abi.v1.ActionResult.switch_model:type_name -> llmsafespaces.abi.v1.SwitchModelResult
	9,  // 8: llmsafespaces.abi.v1.ActionResult.switch_agent:type_name -> llmsafespaces.abi.v1.SwitchAgentResult
	10, // 9: llmsafespaces.abi.v1.ActionResult.answer_question:type_name -> llmsafespaces.abi.v1.AnswerInputResult
	11, // 10: llmsafespaces.abi.v1.ActionResult.compact:type_name -> llmsafespaces.abi.v1.CompactResult
	12, // 11: llmsafespaces.abi.v1.SwitchModelResult.model:type_name -> llmsafespaces.abi.v1.ModelRef
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_llmsafespaces_abi_v1_action_proto_init() }
func file_llmsafespaces_abi_v1_action_proto_init() {
	if File_llmsafespaces_abi_v1_action_proto != nil {
		return
	}
	file_llmsafespaces_abi_v1_contract_proto_init()
	file_llmsafespaces_abi_v1_action_proto_msgTypes[0].OneofWrappers = []any{
		(*ActionRequest_Interrupt)(nil),
		(*ActionRequest_SwitchModel)(nil),
		(*ActionRequest_SwitchAgent)(nil),
		(*ActionRequest_AnswerQuestion)(nil),
		(*ActionRequest_Compact)(nil),
	}
	file_llmsafespaces_abi_v1_action_proto_msgTypes[4].OneofWrappers = []any{}
	file_llmsafespaces_abi_v1_action_proto_msgTypes[6].OneofWrappers = []any{
		(*ActionResult_Interrupt)(nil),
		(*ActionResult_SwitchModel)(nil),
		(*ActionResult_SwitchAgent)(nil),
		(*ActionResult_AnswerQuestion)(nil),
		(*ActionResult_Compact)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_action_proto_rawDesc), len(file_llmsafespaces_abi_v1_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llmsafespaces_abi_v1_action_proto_goTypes,
		DependencyIndexes: file_llmsafespaces_abi_v1_action_proto_depIdxs,
		MessageInfos:      file_llmsafespaces_abi_v1_action_proto_msgTypes,
	}.Build()
	File_llmsafespaces_abi_v1_action_proto = out.File
	file_llmsafespaces_abi_v1_action_proto_goTypes = nil
	file_llmsafespaces_abi_v1_action_proto_depIdxs = nil
}
