// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Capability report (design 0055 M1/M4): provenance, supported actions, and
// supported delivery part types ride the events snapshot frame. Harness
// limits are data: every typed action and part kind is declared here, and
// undeclared capability use returns NotSupported — never an API-side branch.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: llmsafespaces/abi/v1/capability.proto

package abi

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provenance is the 0054 provenance predicate relocated into the report
// (M4): only PLATFORM_PINNED pods with the state-authority surface may arm
// AGENTD_STATE_AUTHORITY; the wiring rejects the rest.
type Provenance int32

const (
	Provenance_PROVENANCE_UNSPECIFIED     Provenance = 0
	Provenance_PROVENANCE_PLATFORM_PINNED Provenance = 1
	Provenance_PROVENANCE_UNPINNED        Provenance = 2
	Provenance_PROVENANCE_BYO             Provenance = 3
)

// Enum value maps for Provenance.
var (
	Provenance_name = map[int32]string{
		0: "PROVENANCE_UNSPECIFIED",
		1: "PROVENANCE_PLATFORM_PINNED",
		2: "PROVENANCE_UNPINNED",
		3: "PROVENANCE_BYO",
	}
	Provenance_value = map[string]int32{
		"PROVENANCE_UNSPECIFIED":     0,
		"PROVENANCE_PLATFORM_PINNED": 1,
		"PROVENANCE_UNPINNED":        2,
		"PROVENANCE_BYO":             3,
	}
)

func (x Provenance) Enum() *Provenance {
	p := new(Provenance)
	*p = x
	return p
}

func (x Provenance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provenance) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_capability_proto_enumTypes[0].Descriptor()
}

func (Provenance) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_capability_proto_enumTypes[0]
}

func (x Provenance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provenance.Descriptor instead.
func (Provenance) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_capability_proto_rawDescGZIP(), []int{0}
}

// ActionType enumerates the op-5 union for capability declaration.
type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED     ActionType = 0
	ActionType_ACTION_TYPE_INTERRUPT       ActionType = 1
	ActionType_ACTION_TYPE_SWITCH_MODEL    ActionType = 2
	ActionType_ACTION_TYPE_SWITCH_AGENT    ActionType = 3
	ActionType_ACTION_TYPE_ANSWER_QUESTION ActionType = 4
	ActionType_ACTION_TYPE_COMPACT         ActionType = 5
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_INTERRUPT",
		2: "ACTION_TYPE_SWITCH_MODEL",
		3: "ACTION_TYPE_SWITCH_AGENT",
		4: "ACTION_TYPE_ANSWER_QUESTION",
		5: "ACTION_TYPE_COMPACT",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED":     0,
		"ACTION_TYPE_INTERRUPT":       1,
		"ACTION_TYPE_SWITCH_MODEL":    2,
		"ACTION_TYPE_SWITCH_AGENT":    3,
		"ACTION_TYPE_ANSWER_QUESTION": 4,
		"ACTION_TYPE_COMPACT":         5,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_capability_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_capability_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_capability_proto_rawDescGZIP(), []int{1}
}

// DeliveryPartKind enumerates delivery part kinds for capability
// declaration. opencode on 1.18.x declares TEXT only (D3).
type DeliveryPartKind int32

const (
	DeliveryPartKind_DELIVERY_PART_KIND_UNSPECIFIED DeliveryPartKind = 0
	DeliveryPartKind_DELIVERY_PART_KIND_TEXT        DeliveryPartKind = 1
	DeliveryPartKind_DELIVERY_PART_KIND_FILE        DeliveryPartKind = 2
)

// Enum value maps for DeliveryPartKind.
var (
	DeliveryPartKind_name = map[int32]string{
		0: "DELIVERY_PART_KIND_UNSPECIFIED",
		1: "DELIVERY_PART_KIND_TEXT",
		2: "DELIVERY_PART_KIND_FILE",
	}
	DeliveryPartKind_value = map[string]int32{
		"DELIVERY_PART_KIND_UNSPECIFIED": 0,
		"DELIVERY_PART_KIND_TEXT":        1,
		"DELIVERY_PART_KIND_FILE":        2,
	}
)

func (x DeliveryPartKind) Enum() *DeliveryPartKind {
	p := new(DeliveryPartKind)
	*p = x
	return p
}

func (x DeliveryPartKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryPartKind) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_capability_proto_enumTypes[2].Descriptor()
}

func (DeliveryPartKind) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_capability_proto_enumTypes[2]
}

func (x DeliveryPartKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryPartKind.Descriptor instead.
func (DeliveryPartKind) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_capability_proto_rawDescGZIP(), []int{2}
}

type CapabilityReport struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Provenance             Provenance             `protobuf:"varint,1,opt,name=provenance,proto3,enum=llmsafespaces.abi.v1.Provenance" json:"provenance,omitempty"`
	Harness                string                 `protobuf:"bytes,2,opt,name=harness,proto3" json:"harness,omitempty"`
	HarnessVersion         string                 `protobuf:"bytes,3,opt,name=harness_version,json=harnessVersion,proto3" json:"harness_version,omitempty"`
	AgentdVersion          string                 `protobuf:"bytes,4,opt,name=agentd_version,json=agentdVersion,proto3" json:"agentd_version,omitempty"`
	SupportedActions       []ActionType           `protobuf:"varint,5,rep,packed,name=supported_actions,json=supportedActions,proto3,enum=llmsafespaces.abi.v1.ActionType" json:"supported_actions,omitempty"`
	SupportedDeliveryParts []DeliveryPartKind     `protobuf:"varint,6,rep,packed,name=supported_delivery_parts,json=supportedDeliveryParts,proto3,enum=llmsafespaces.abi.v1.DeliveryPartKind" json:"supported_delivery_parts,omitempty"`
	AbiVersion             string                 `protobuf:"bytes,7,opt,name=abi_version,json=abiVersion,proto3" json:"abi_version,omitempty"`
	// v2_delivery reports whether the harness's V2 session runner surface is
	// present (the M4 flag-matrix "surface present" predicate).
	V2Delivery    bool `protobuf:"varint,8,opt,name=v2_delivery,json=v2Delivery,proto3" json:"v2_delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityReport) Reset() {
	*x = CapabilityReport{}
	mi := &file_llmsafespaces_abi_v1_capability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityReport) ProtoMessage() {}

func (x *CapabilityReport) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_capability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityReport.ProtoReflect.Descriptor instead.
func (*CapabilityReport) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_capability_proto_rawDescGZIP(), []int{0}
}

func (x *CapabilityReport) GetProvenance() Provenance {
	if x != nil {
		return x.Provenance
	}
	return Provenance_PROVENANCE_UNSPECIFIED
}

func (x *CapabilityReport) GetHarness() string {
	if x != nil {
		return x.Harness
	}
	return ""
}

func (x *CapabilityReport) GetHarnessVersion() string {
	if x != nil {
		return x.HarnessVersion
	}
	return ""
}

func (x *CapabilityReport) GetAgentdVersion() string {
	if x != nil {
		return x.AgentdVersion
	}
	return ""
}

func (x *CapabilityReport) GetSupportedActions() []ActionType {
	if x != nil {
		return x.SupportedActions
	}
	return nil
}

func (x *CapabilityReport) GetSupportedDeliveryParts() []DeliveryPartKind {
	if x != nil {
		return x.SupportedDeliveryParts
	}
	return nil
}

func (x *CapabilityReport) GetAbiVersion() string {
	if x != nil {
		return x.AbiVersion
	}
	return ""
}

func (x *CapabilityReport) GetV2Delivery() bool {
	if x != nil {
		return x.V2Delivery
	}
	return false
}

// NotSupported is the typed error detail for capability-gated refusals —
// undeclared actions and undeclared delivery part kinds. It rides connect
// CodeUnimplemented errors, so the refusal survives every codec.
type NotSupported struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotSupported) Reset() {
	*x = NotSupported{}
	mi := &file_llmsafespaces_abi_v1_capability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotSupported) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotSupported) ProtoMessage() {}

func (x *NotSupported) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_capability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotSupported.ProtoReflect.Descriptor instead.
func (*NotSupported) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_capability_proto_rawDescGZIP(), []int{1}
}

func (x *NotSupported) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *NotSupported) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_llmsafespaces_abi_v1_capability_proto protoreflect.FileDescriptor

const file_llmsafespaces_abi_v1_capability_proto_rawDesc = "" +
	"\n" +
	"%llmsafespaces/abi/v1/capability.proto\x12\x14llmsafespaces.abi.v1\"\xb1\x03\n" +
	"\x10CapabilityReport\x12@\n" +
	"\n" +
	"provenance\x18\x01 \x01(\x0e2 .llmsafespaces.abi.v1.ProvenanceR\n" +
	"provenance\x12\x18\n" +
	"\aharness\x18\x02 \x01(\tR\aharness\x12'\n" +
	"\x0fharness_version\x18\x03 \x01(\tR\x0eharnessVersion\x12%\n" +
	"\x0eagentd_version\x18\x04 \x01(\tR\ragentdVersion\x12M\n" +
	"\x11supported_actions\x18\x05 \x03(\x0e2 .llmsafespaces.abi.v1.ActionTypeR\x10supportedActions\x12`\n" +
	"\x18supported_delivery_parts\x18\x06 \x03(\x0e2&.llmsafespaces.abi.v1.DeliveryPartKindR\x16supportedDeliveryParts\x12\x1f\n" +
	"\vabi_version\x18\a \x01(\tR\n" +
	"abiVersion\x12\x1f\n" +
	"\vv2_delivery\x18\b \x01(\bR\n" +
	"v2Delivery\"F\n" +
	"\fNotSupported\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail*u\n" +
	"\n" +
	"Provenance\x12\x1a\n" +
	"\x16PROVENANCE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPROVENANCE_PLATFORM_PINNED\x10\x01\x12\x17\n" +
	"\x13PROVENANCE_UNPINNED\x10\x02\x12\x12\n" +
	"\x0ePROVENANCE_BYO\x10\x03*\xba\x01\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACTION_TYPE_INTERRUPT\x10\x01\x12\x1c\n" +
	"\x18ACTION_TYPE_SWITCH_MODEL\x10\x02\x12\x1c\n" +
	"\x18ACTION_TYPE_SWITCH_AGENT\x10\x03\x12\x1f\n" +
	"\x1bACTION_TYPE_ANSWER_QUESTION\x10\x04\x12\x17\n" +
	"\x13ACTION_TYPE_COMPACT\x10\x05*p\n" +
	"\x10DeliveryPartKind\x12\"\n" +
	"\x1eDELIVERY_PART_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DELIVERY_PART_KIND_TEXT\x10\x01\x12\x1b\n" +
	"\x17DELIVERY_PART_KIND_FILE\x10\x02B1Z/github.com/lenaxia/llmsafespaces/pkg/abi/v1;abib\x06proto3"

var (
	file_llmsafespaces_abi_v1_capability_proto_rawDescOnce sync.Once
	file_llmsafespaces_abi_v1_capability_proto_rawDescData []byte
)

func file_llmsafespaces_abi_v1_capability_proto_rawDescGZIP() []byte {
	file_llmsafespaces_abi_v1_capability_proto_rawDescOnce.Do(func() {
		file_llmsafespaces_abi_v1_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_capability_proto_rawDesc), len(file_llmsafespaces_abi_v1_capability_proto_rawDesc)))
	})
	return file_llmsafespaces_abi_v1_capability_proto_rawDescData
}

var file_llmsafespaces_abi_v1_capability_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_llmsafespaces_abi_v1_capability_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_llmsafespaces_abi_v1_capability_proto_goTypes = []any{
	(Provenance)(0),          // 0: llmsafespaces.abi.v1.Provenance
	(ActionType)(0),          // 1: llmsafespaces.abi.v1.ActionType
	(DeliveryPartKind)(0),    // 2: llmsafespaces.abi.v1.DeliveryPartKind
	(*CapabilityReport)(nil), // 3: llmsafespaces.abi.v1.CapabilityReport
	(*NotSupported)(nil),     // 4: llmsafespaces.abi.v1.NotSupported
}
var file_llmsafespaces_abi_v1_capability_proto_depIdxs = []int32{
	0, // 0: llmsafespaces.abi.v1.CapabilityReport.provenance:type_name -> llmsafespaces.abi.v1.Provenance
	1, // 1: llmsafespaces.abi.v1.CapabilityReport.supported_actions:type_name -> llmsafespaces.abi.v1.ActionType
	2, // 2: llmsafespaces.abi.v1.CapabilityReport.supported_delivery_parts:type_name -> llmsafespaces.abi.v1.DeliveryPartKind
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_llmsafespaces_abi_v1_capability_proto_init() }
func file_llmsafespaces_abi_v1_capability_proto_init() {
	if File_llmsafespaces_abi_v1_capability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_capability_proto_rawDesc), len(file_llmsafespaces_abi_v1_capability_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llmsafespaces_abi_v1_capability_proto_goTypes,
		DependencyIndexes: file_llmsafespaces_abi_v1_capability_proto_depIdxs,
		EnumInfos:         file_llmsafespaces_abi_v1_capability_proto_enumTypes,
		MessageInfos:      file_llmsafespaces_abi_v1_capability_proto_msgTypes,
	}.Build()
	File_llmsafespaces_abi_v1_capability_proto = out.File
	file_llmsafespaces_abi_v1_capability_proto_goTypes = nil
	file_llmsafespaces_abi_v1_capability_proto_depIdxs = nil
}
