// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The Epic 65 agent session contract (design 0049, mirrored in
// pkg/session) expressed as ABI schema messages. Parity with pkg/session is
// enforced field-by-field and enum-by-enum by TestPkgSessionContractParity.
// Until the S2 freeze flips pkg/session to generated types (ADR 0056), these
// two representations must stay equivalent — the parity test fails CI on
// drift in either direction.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: llmsafespaces/abi/v1/contract.proto

package abi

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionStatus is the lifecycle state of an agent session. UNKNOWN is a
// contract-real non-zero state; the zero value is never a valid status.
type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_UNKNOWN     SessionStatus = 1
	SessionStatus_SESSION_STATUS_IDLE        SessionStatus = 2
	SessionStatus_SESSION_STATUS_BUSY        SessionStatus = 3
	SessionStatus_SESSION_STATUS_ERROR       SessionStatus = 4
	SessionStatus_SESSION_STATUS_COMPACTING  SessionStatus = 5
	SessionStatus_SESSION_STATUS_ARCHIVED    SessionStatus = 6
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_UNKNOWN",
		2: "SESSION_STATUS_IDLE",
		3: "SESSION_STATUS_BUSY",
		4: "SESSION_STATUS_ERROR",
		5: "SESSION_STATUS_COMPACTING",
		6: "SESSION_STATUS_ARCHIVED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_UNKNOWN":     1,
		"SESSION_STATUS_IDLE":        2,
		"SESSION_STATUS_BUSY":        3,
		"SESSION_STATUS_ERROR":       4,
		"SESSION_STATUS_COMPACTING":  5,
		"SESSION_STATUS_ARCHIVED":    6,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_contract_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_contract_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{0}
}

// PartType is the closed part union — 5 types forever (design 0049 §4.1
// rule 1). Adding a value is a contract change, not a schema edit.
type PartType int32

const (
	PartType_PART_TYPE_UNSPECIFIED PartType = 0
	PartType_PART_TYPE_TEXT        PartType = 1
	PartType_PART_TYPE_REASONING   PartType = 2
	PartType_PART_TYPE_TOOL        PartType = 3
	PartType_PART_TYPE_FILE_CHANGE PartType = 4
	PartType_PART_TYPE_CUSTOM      PartType = 5
)

// Enum value maps for PartType.
var (
	PartType_name = map[int32]string{
		0: "PART_TYPE_UNSPECIFIED",
		1: "PART_TYPE_TEXT",
		2: "PART_TYPE_REASONING",
		3: "PART_TYPE_TOOL",
		4: "PART_TYPE_FILE_CHANGE",
		5: "PART_TYPE_CUSTOM",
	}
	PartType_value = map[string]int32{
		"PART_TYPE_UNSPECIFIED": 0,
		"PART_TYPE_TEXT":        1,
		"PART_TYPE_REASONING":   2,
		"PART_TYPE_TOOL":        3,
		"PART_TYPE_FILE_CHANGE": 4,
		"PART_TYPE_CUSTOM":      5,
	}
)

func (x PartType) Enum() *PartType {
	p := new(PartType)
	*p = x
	return p
}

func (x PartType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartType) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_contract_proto_enumTypes[1].Descriptor()
}

func (PartType) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_contract_proto_enumTypes[1]
}

func (x PartType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartType.Descriptor instead.
func (PartType) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{1}
}

type ToolStatus int32

const (
	ToolStatus_TOOL_STATUS_UNSPECIFIED ToolStatus = 0
	ToolStatus_TOOL_STATUS_PENDING     ToolStatus = 1
	ToolStatus_TOOL_STATUS_RUNNING     ToolStatus = 2
	ToolStatus_TOOL_STATUS_COMPLETED   ToolStatus = 3
	ToolStatus_TOOL_STATUS_ERROR       ToolStatus = 4
)

// Enum value maps for ToolStatus.
var (
	ToolStatus_name = map[int32]string{
		0: "TOOL_STATUS_UNSPECIFIED",
		1: "TOOL_STATUS_PENDING",
		2: "TOOL_STATUS_RUNNING",
		3: "TOOL_STATUS_COMPLETED",
		4: "TOOL_STATUS_ERROR",
	}
	ToolStatus_value = map[string]int32{
		"TOOL_STATUS_UNSPECIFIED": 0,
		"TOOL_STATUS_PENDING":     1,
		"TOOL_STATUS_RUNNING":     2,
		"TOOL_STATUS_COMPLETED":   3,
		"TOOL_STATUS_ERROR":       4,
	}
)

func (x ToolStatus) Enum() *ToolStatus {
	p := new(ToolStatus)
	*p = x
	return p
}

func (x ToolStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_contract_proto_enumTypes[2].Descriptor()
}

func (ToolStatus) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_contract_proto_enumTypes[2]
}

func (x ToolStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolStatus.Descriptor instead.
func (ToolStatus) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{2}
}

type ChangeStatus int32

const (
	ChangeStatus_CHANGE_STATUS_UNSPECIFIED ChangeStatus = 0
	ChangeStatus_CHANGE_STATUS_ADDED       ChangeStatus = 1
	ChangeStatus_CHANGE_STATUS_MODIFIED    ChangeStatus = 2
	ChangeStatus_CHANGE_STATUS_DELETED     ChangeStatus = 3
	ChangeStatus_CHANGE_STATUS_RENAMED     ChangeStatus = 4
)

// Enum value maps for ChangeStatus.
var (
	ChangeStatus_name = map[int32]string{
		0: "CHANGE_STATUS_UNSPECIFIED",
		1: "CHANGE_STATUS_ADDED",
		2: "CHANGE_STATUS_MODIFIED",
		3: "CHANGE_STATUS_DELETED",
		4: "CHANGE_STATUS_RENAMED",
	}
	ChangeStatus_value = map[string]int32{
		"CHANGE_STATUS_UNSPECIFIED": 0,
		"CHANGE_STATUS_ADDED":       1,
		"CHANGE_STATUS_MODIFIED":    2,
		"CHANGE_STATUS_DELETED":     3,
		"CHANGE_STATUS_RENAMED":     4,
	}
)

func (x ChangeStatus) Enum() *ChangeStatus {
	p := new(ChangeStatus)
	*p = x
	return p
}

func (x ChangeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_contract_proto_enumTypes[3].Descriptor()
}

func (ChangeStatus) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_contract_proto_enumTypes[3]
}

func (x ChangeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeStatus.Descriptor instead.
func (ChangeStatus) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{3}
}

// MessageType discriminates a transcript entry (design 0049 §4.5).
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED  MessageType = 0
	MessageType_MESSAGE_TYPE_USER         MessageType = 1
	MessageType_MESSAGE_TYPE_ASSISTANT    MessageType = 2
	MessageType_MESSAGE_TYPE_SHELL        MessageType = 3
	MessageType_MESSAGE_TYPE_AGENT_SWITCH MessageType = 4
	MessageType_MESSAGE_TYPE_MODEL_SWITCH MessageType = 5
	MessageType_MESSAGE_TYPE_COMPACTION   MessageType = 6
	MessageType_MESSAGE_TYPE_SYSTEM       MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_USER",
		2: "MESSAGE_TYPE_ASSISTANT",
		3: "MESSAGE_TYPE_SHELL",
		4: "MESSAGE_TYPE_AGENT_SWITCH",
		5: "MESSAGE_TYPE_MODEL_SWITCH",
		6: "MESSAGE_TYPE_COMPACTION",
		7: "MESSAGE_TYPE_SYSTEM",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":  0,
		"MESSAGE_TYPE_USER":         1,
		"MESSAGE_TYPE_ASSISTANT":    2,
		"MESSAGE_TYPE_SHELL":        3,
		"MESSAGE_TYPE_AGENT_SWITCH": 4,
		"MESSAGE_TYPE_MODEL_SWITCH": 5,
		"MESSAGE_TYPE_COMPACTION":   6,
		"MESSAGE_TYPE_SYSTEM":       7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_contract_proto_enumTypes[4].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_contract_proto_enumTypes[4]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{4}
}

// EventType is the contract's pinned event set. The ABI's synthetic stream
// control notices (snapshot frame, reseed) are NOT contract events; they are
// frame types on the stream (abi.proto).
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED     EventType = 0
	EventType_EVENT_TYPE_SESSION_STATUS  EventType = 1
	EventType_EVENT_TYPE_SESSION_UPDATED EventType = 2
	EventType_EVENT_TYPE_MESSAGE_START   EventType = 3
	EventType_EVENT_TYPE_MESSAGE_END     EventType = 4
	EventType_EVENT_TYPE_PART_START      EventType = 5
	EventType_EVENT_TYPE_PART_DELTA      EventType = 6
	EventType_EVENT_TYPE_PART_END        EventType = 7
	EventType_EVENT_TYPE_INPUT_REQUEST   EventType = 8
	EventType_EVENT_TYPE_INPUT_RESOLVED  EventType = 9
	EventType_EVENT_TYPE_ERROR           EventType = 10
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_SESSION_STATUS",
		2:  "EVENT_TYPE_SESSION_UPDATED",
		3:  "EVENT_TYPE_MESSAGE_START",
		4:  "EVENT_TYPE_MESSAGE_END",
		5:  "EVENT_TYPE_PART_START",
		6:  "EVENT_TYPE_PART_DELTA",
		7:  "EVENT_TYPE_PART_END",
		8:  "EVENT_TYPE_INPUT_REQUEST",
		9:  "EVENT_TYPE_INPUT_RESOLVED",
		10: "EVENT_TYPE_ERROR",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":     0,
		"EVENT_TYPE_SESSION_STATUS":  1,
		"EVENT_TYPE_SESSION_UPDATED": 2,
		"EVENT_TYPE_MESSAGE_START":   3,
		"EVENT_TYPE_MESSAGE_END":     4,
		"EVENT_TYPE_PART_START":      5,
		"EVENT_TYPE_PART_DELTA":      6,
		"EVENT_TYPE_PART_END":        7,
		"EVENT_TYPE_INPUT_REQUEST":   8,
		"EVENT_TYPE_INPUT_RESOLVED":  9,
		"EVENT_TYPE_ERROR":           10,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_contract_proto_enumTypes[5].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_contract_proto_enumTypes[5]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{5}
}

// InputKind unifies questions and permissions: both are "the agent needs a
// human" (design 0049 §4.5).
type InputKind int32

const (
	InputKind_INPUT_KIND_UNSPECIFIED InputKind = 0
	InputKind_INPUT_KIND_QUESTION    InputKind = 1
	InputKind_INPUT_KIND_PERMISSION  InputKind = 2
)

// Enum value maps for InputKind.
var (
	InputKind_name = map[int32]string{
		0: "INPUT_KIND_UNSPECIFIED",
		1: "INPUT_KIND_QUESTION",
		2: "INPUT_KIND_PERMISSION",
	}
	InputKind_value = map[string]int32{
		"INPUT_KIND_UNSPECIFIED": 0,
		"INPUT_KIND_QUESTION":    1,
		"INPUT_KIND_PERMISSION":  2,
	}
)

func (x InputKind) Enum() *InputKind {
	p := new(InputKind)
	*p = x
	return p
}

func (x InputKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputKind) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_contract_proto_enumTypes[6].Descriptor()
}

func (InputKind) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_contract_proto_enumTypes[6]
}

func (x InputKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InputKind.Descriptor instead.
func (InputKind) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{6}
}

// TimeRange bounds a session or message. completed_at is unset while busy.
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRange) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TimeRange) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// Cost is display-only token/cost data. Billing is cgroup-based; these
// fields are never authoritative for metering (design 0049 §4.1 rule 5).
type Cost struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputTokens      int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens     int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	ReasoningTokens  int64                  `protobuf:"varint,3,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	CacheReadTokens  int64                  `protobuf:"varint,4,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	CacheWriteTokens int64                  `protobuf:"varint,5,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	TotalTokens      int64                  `protobuf:"varint,6,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CostUsd          float64                `protobuf:"fixed64,7,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Cost) Reset() {
	*x = Cost{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cost) ProtoMessage() {}

func (x *Cost) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cost.ProtoReflect.Descriptor instead.
func (*Cost) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{1}
}

func (x *Cost) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Cost) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Cost) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *Cost) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *Cost) GetCacheWriteTokens() int64 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

func (x *Cost) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Cost) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

// ContextUsage is the session's live context occupancy. Non-monotonic by
// design: compaction resets it.
type ContextUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Used          int64                  `protobuf:"varint,1,opt,name=used,proto3" json:"used,omitempty"`
	Window        int64                  `protobuf:"varint,2,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextUsage) Reset() {
	*x = ContextUsage{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUsage) ProtoMessage() {}

func (x *ContextUsage) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUsage.ProtoReflect.Descriptor instead.
func (*ContextUsage) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{2}
}

func (x *ContextUsage) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *ContextUsage) GetWindow() int64 {
	if x != nil {
		return x.Window
	}
	return 0
}

// ModelRef identifies a model an adapter selected for a session or message.
type ModelRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelRef) Reset() {
	*x = ModelRef{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRef) ProtoMessage() {}

func (x *ModelRef) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRef.ProtoReflect.Descriptor instead.
func (*ModelRef) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{3}
}

func (x *ModelRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelRef) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

// Session is the platform-owned view of one agent session. Agent/model
// switches and compaction ride the transcript as Messages, not side-band
// fields here (design 0049 §4.5).
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	AgentId       string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Model         *ModelRef              `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Status        SessionStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=llmsafespaces.abi.v1.SessionStatus" json:"status,omitempty"`
	Cost          *Cost                  `protobuf:"bytes,8,opt,name=cost,proto3" json:"cost,omitempty"`
	ContextUsage  *ContextUsage          `protobuf:"bytes,9,opt,name=context_usage,json=contextUsage,proto3" json:"context_usage,omitempty"`
	Time          *TimeRange             `protobuf:"bytes,10,opt,name=time,proto3" json:"time,omitempty"`
	Summary       string                 `protobuf:"bytes,11,opt,name=summary,proto3" json:"summary,omitempty"`
	Archived      bool                   `protobuf:"varint,12,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{4}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Session) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Session) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Session) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Session) GetModel() *ModelRef {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *Session) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *Session) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Session) GetContextUsage() *ContextUsage {
	if x != nil {
		return x.ContextUsage
	}
	return nil
}

func (x *Session) GetTime() *TimeRange {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Session) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Session) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

// ToolState is the lifecycle state of one tool call.
type ToolState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ToolStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=llmsafespaces.abi.v1.ToolStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolState) Reset() {
	*x = ToolState{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolState) ProtoMessage() {}

func (x *ToolState) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolState.ProtoReflect.Descriptor instead.
func (*ToolState) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{5}
}

func (x *ToolState) GetStatus() ToolStatus {
	if x != nil {
		return x.Status
	}
	return ToolStatus_TOOL_STATUS_UNSPECIFIED
}

func (x *ToolState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolState) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ToolState) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// ToolPart is the payload of a Tool part: every tool call discriminated by
// name (design 0049 §4.1 rule 2). input/output carry raw JSON because tool
// schemas are open-ended; adapters and renderers decode per name.
type ToolPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Input         []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Output        []byte                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	State         *ToolState             `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolPart) Reset() {
	*x = ToolPart{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolPart) ProtoMessage() {}

func (x *ToolPart) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolPart.ProtoReflect.Descriptor instead.
func (*ToolPart) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{6}
}

func (x *ToolPart) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolPart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolPart) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ToolPart) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ToolPart) GetState() *ToolState {
	if x != nil {
		return x.State
	}
	return nil
}

// FileDiff is the payload of a FileChange part. patch is authoritative
// unified-diff text — no hunk structs (design 0049 §4.1 rule 4).
type FileDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	OldPath       string                 `protobuf:"bytes,2,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	Status        ChangeStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=llmsafespaces.abi.v1.ChangeStatus" json:"status,omitempty"`
	Patch         string                 `protobuf:"bytes,4,opt,name=patch,proto3" json:"patch,omitempty"`
	Additions     int32                  `protobuf:"varint,5,opt,name=additions,proto3" json:"additions,omitempty"`
	Deletions     int32                  `protobuf:"varint,6,opt,name=deletions,proto3" json:"deletions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDiff) Reset() {
	*x = FileDiff{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDiff) ProtoMessage() {}

func (x *FileDiff) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDiff.ProtoReflect.Descriptor instead.
func (*FileDiff) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{7}
}

func (x *FileDiff) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDiff) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *FileDiff) GetStatus() ChangeStatus {
	if x != nil {
		return x.Status
	}
	return ChangeStatus_CHANGE_STATUS_UNSPECIFIED
}

func (x *FileDiff) GetPatch() string {
	if x != nil {
		return x.Patch
	}
	return ""
}

func (x *FileDiff) GetAdditions() int32 {
	if x != nil {
		return x.Additions
	}
	return 0
}

func (x *FileDiff) GetDeletions() int32 {
	if x != nil {
		return x.Deletions
	}
	return 0
}

// CustomPart is the pressure-relief valve for extension-defined semantics
// (design 0049 §4.3). kind is required; data carries raw JSON.
type CustomPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomPart) Reset() {
	*x = CustomPart{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomPart) ProtoMessage() {}

func (x *CustomPart) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomPart.ProtoReflect.Descriptor instead.
func (*CustomPart) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{8}
}

func (x *CustomPart) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CustomPart) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Part is one typed piece of an assistant message. type is the authoritative
// discriminator; the oneof payload mirrors it 1:1 — both are set together.
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  PartType               `protobuf:"varint,2,opt,name=type,proto3,enum=llmsafespaces.abi.v1.PartType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Part_Text
	//	*Part_Reasoning
	//	*Part_Tool
	//	*Part_FileChange
	//	*Part_Custom
	Payload       isPart_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{9}
}

func (x *Part) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Part) GetType() PartType {
	if x != nil {
		return x.Type
	}
	return PartType_PART_TYPE_UNSPECIFIED
}

func (x *Part) GetPayload() isPart_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Part) GetText() string {
	if x != nil {
		if x, ok := x.Payload.(*Part_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Part) GetReasoning() string {
	if x != nil {
		if x, ok := x.Payload.(*Part_Reasoning); ok {
			return x.Reasoning
		}
	}
	return ""
}

func (x *Part) GetTool() *ToolPart {
	if x != nil {
		if x, ok := x.Payload.(*Part_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *Part) GetFileChange() *FileDiff {
	if x != nil {
		if x, ok := x.Payload.(*Part_FileChange); ok {
			return x.FileChange
		}
	}
	return nil
}

func (x *Part) GetCustom() *CustomPart {
	if x != nil {
		if x, ok := x.Payload.(*Part_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

type isPart_Payload interface {
	isPart_Payload()
}

type Part_Text struct {
	Text string `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type Part_Reasoning struct {
	Reasoning string `protobuf:"bytes,4,opt,name=reasoning,proto3,oneof"`
}

type Part_Tool struct {
	Tool *ToolPart `protobuf:"bytes,5,opt,name=tool,proto3,oneof"`
}

type Part_FileChange struct {
	FileChange *FileDiff `protobuf:"bytes,6,opt,name=file_change,json=fileChange,proto3,oneof"`
}

type Part_Custom struct {
	Custom *CustomPart `protobuf:"bytes,7,opt,name=custom,proto3,oneof"`
}

func (*Part_Text) isPart_Payload() {}

func (*Part_Reasoning) isPart_Payload() {}

func (*Part_Tool) isPart_Payload() {}

func (*Part_FileChange) isPart_Payload() {}

func (*Part_Custom) isPart_Payload() {}

// Message is one entry in a session transcript: a flat discriminated record
// where type selects which payload fields are meaningful.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=llmsafespaces.abi.v1.MessageType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	Parts         []*Part                `protobuf:"bytes,5,rep,name=parts,proto3" json:"parts,omitempty"`
	Model         *ModelRef              `protobuf:"bytes,6,opt,name=model,proto3,oneof" json:"model,omitempty"`
	Cost          *Cost                  `protobuf:"bytes,7,opt,name=cost,proto3,oneof" json:"cost,omitempty"`
	Text          string                 `protobuf:"bytes,8,opt,name=text,proto3" json:"text,omitempty"`
	Command       string                 `protobuf:"bytes,9,opt,name=command,proto3" json:"command,omitempty"`
	ExitCode      *int32                 `protobuf:"varint,10,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	FromAgent     string                 `protobuf:"bytes,11,opt,name=from_agent,json=fromAgent,proto3" json:"from_agent,omitempty"`
	ToAgent       string                 `protobuf:"bytes,12,opt,name=to_agent,json=toAgent,proto3" json:"to_agent,omitempty"`
	FromModel     *ModelRef              `protobuf:"bytes,13,opt,name=from_model,json=fromModel,proto3,oneof" json:"from_model,omitempty"`
	ToModel       *ModelRef              `protobuf:"bytes,14,opt,name=to_model,json=toModel,proto3,oneof" json:"to_model,omitempty"`
	Error         *Error                 `protobuf:"bytes,15,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{10}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Message) GetModel() *ModelRef {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *Message) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Message) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *Message) GetFromAgent() string {
	if x != nil {
		return x.FromAgent
	}
	return ""
}

func (x *Message) GetToAgent() string {
	if x != nil {
		return x.ToAgent
	}
	return ""
}

func (x *Message) GetFromModel() *ModelRef {
	if x != nil {
		return x.FromModel
	}
	return nil
}

func (x *Message) GetToModel() *ModelRef {
	if x != nil {
		return x.ToModel
	}
	return nil
}

func (x *Message) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Error is the payload of an error event (and an assistant message's error
// field). Deliberately not a PartType — the part union stays closed.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{11}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// InputOption is one selectable choice within a question input request.
type InputOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputOption) Reset() {
	*x = InputOption{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputOption) ProtoMessage() {}

func (x *InputOption) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputOption.ProtoReflect.Descriptor instead.
func (*InputOption) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{12}
}

func (x *InputOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *InputOption) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ToolRef identifies the tool call that triggered an input request, if any.
type ToolRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRef) Reset() {
	*x = ToolRef{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRef) ProtoMessage() {}

func (x *ToolRef) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRef.ProtoReflect.Descriptor instead.
func (*ToolRef) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{13}
}

func (x *ToolRef) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ToolRef) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// InputRequest is the unified pending-input shape. Question fields apply
// when kind = QUESTION; permission fields when kind = PERMISSION. metadata
// values carry raw JSON (open-ended extension data).
type InputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RootSessionId string                 `protobuf:"bytes,3,opt,name=root_session_id,json=rootSessionId,proto3" json:"root_session_id,omitempty"`
	Kind          InputKind              `protobuf:"varint,4,opt,name=kind,proto3,enum=llmsafespaces.abi.v1.InputKind" json:"kind,omitempty"`
	Question      string                 `protobuf:"bytes,5,opt,name=question,proto3" json:"question,omitempty"`
	Header        string                 `protobuf:"bytes,6,opt,name=header,proto3" json:"header,omitempty"`
	Options       []*InputOption         `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	Multiple      bool                   `protobuf:"varint,8,opt,name=multiple,proto3" json:"multiple,omitempty"`
	Custom        bool                   `protobuf:"varint,9,opt,name=custom,proto3" json:"custom,omitempty"`
	Permission    string                 `protobuf:"bytes,10,opt,name=permission,proto3" json:"permission,omitempty"`
	Patterns      []string               `protobuf:"bytes,11,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Always        []string               `protobuf:"bytes,12,rep,name=always,proto3" json:"always,omitempty"`
	Metadata      map[string][]byte      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tool          *ToolRef               `protobuf:"bytes,14,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputRequest) Reset() {
	*x = InputRequest{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRequest) ProtoMessage() {}

func (x *InputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRequest.ProtoReflect.Descriptor instead.
func (*InputRequest) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{14}
}

func (x *InputRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InputRequest) GetRootSessionId() string {
	if x != nil {
		return x.RootSessionId
	}
	return ""
}

func (x *InputRequest) GetKind() InputKind {
	if x != nil {
		return x.Kind
	}
	return InputKind_INPUT_KIND_UNSPECIFIED
}

func (x *InputRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *InputRequest) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *InputRequest) GetOptions() []*InputOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *InputRequest) GetMultiple() bool {
	if x != nil {
		return x.Multiple
	}
	return false
}

func (x *InputRequest) GetCustom() bool {
	if x != nil {
		return x.Custom
	}
	return false
}

func (x *InputRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *InputRequest) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *InputRequest) GetAlways() []string {
	if x != nil {
		return x.Always
	}
	return nil
}

func (x *InputRequest) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InputRequest) GetTool() *ToolRef {
	if x != nil {
		return x.Tool
	}
	return nil
}

// Event is one item on a session's streaming event stream. type selects
// which payload fields are meaningful; the rest stay unset.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=llmsafespaces.abi.v1.EventType" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PartId        string                 `protobuf:"bytes,5,opt,name=part_id,json=partId,proto3" json:"part_id,omitempty"`
	Status        SessionStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=llmsafespaces.abi.v1.SessionStatus" json:"status,omitempty"`
	Session       *Session               `protobuf:"bytes,7,opt,name=session,proto3" json:"session,omitempty"`
	Message       *Message               `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Part          *Part                  `protobuf:"bytes,9,opt,name=part,proto3" json:"part,omitempty"`
	Delta         string                 `protobuf:"bytes,10,opt,name=delta,proto3" json:"delta,omitempty"`
	Input         *InputRequest          `protobuf:"bytes,11,opt,name=input,proto3" json:"input,omitempty"`
	Error         *Error                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_contract_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP(), []int{15}
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Event) GetPartId() string {
	if x != nil {
		return x.PartId
	}
	return ""
}

func (x *Event) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *Event) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *Event) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Event) GetPart() *Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *Event) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *Event) GetInput() *InputRequest {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Event) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_llmsafespaces_abi_v1_contract_proto protoreflect.FileDescriptor

const file_llmsafespaces_abi_v1_contract_proto_rawDesc = "" +
	"\n" +
	"#llmsafespaces/abi/v1/contract.proto\x12\x14llmsafespaces.abi.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n" +
	"\tTimeRange\x129\n" +
	"\n" +
	"started_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12B\n" +
	"\fcompleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vcompletedAt\x88\x01\x01B\x0f\n" +
	"\r_completed_at\"\x91\x02\n" +
	"\x04Cost\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x03 \x01(\x03R\x0freasoningTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x04 \x01(\x03R\x0fcacheReadTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x05 \x01(\x03R\x10cacheWriteTokens\x12!\n" +
	"\ftotal_tokens\x18\x06 \x01(\x03R\vtotalTokens\x12\x19\n" +
	"\bcost_usd\x18\a \x01(\x01R\acostUsd\":\n" +
	"\fContextUsage\x12\x12\n" +
	"\x04used\x18\x01 \x01(\x03R\x04used\x12\x16\n" +
	"\x06window\x18\x02 \x01(\x03R\x06window\"6\n" +
	"\bModelRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\xe1\x03\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x124\n" +
	"\x05model\x18\x06 \x01(\v2\x1e.llmsafespaces.abi.v1.ModelRefR\x05model\x12;\n" +
	"\x06status\x18\a \x01(\x0e2#.llmsafespaces.abi.v1.SessionStatusR\x06status\x12.\n" +
	"\x04cost\x18\b \x01(\v2\x1a.llmsafespaces.abi.v1.CostR\x04cost\x12G\n" +
	"\rcontext_usage\x18\t \x01(\v2\".llmsafespaces.abi.v1.ContextUsageR\fcontextUsage\x123\n" +
	"\x04time\x18\n" +
	" \x01(\v2\x1f.llmsafespaces.abi.v1.TimeRangeR\x04time\x12\x18\n" +
	"\asummary\x18\v \x01(\tR\asummary\x12\x1a\n" +
	"\barchived\x18\f \x01(\bR\barchived\"\xff\x01\n" +
	"\tToolState\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .llmsafespaces.abi.v1.ToolStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12>\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartedAt\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcompletedAt\x88\x01\x01B\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_at\"\x9c\x01\n" +
	"\bToolPart\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\x12\x16\n" +
	"\x06output\x18\x04 \x01(\fR\x06output\x125\n" +
	"\x05state\x18\x05 \x01(\v2\x1f.llmsafespaces.abi.v1.ToolStateR\x05state\"\xc7\x01\n" +
	"\bFileDiff\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bold_path\x18\x02 \x01(\tR\aoldPath\x12:\n" +
	"\x06status\x18\x03 \x01(\x0e2\".llmsafespaces.abi.v1.ChangeStatusR\x06status\x12\x14\n" +
	"\x05patch\x18\x04 \x01(\tR\x05patch\x12\x1c\n" +
	"\tadditions\x18\x05 \x01(\x05R\tadditions\x12\x1c\n" +
	"\tdeletions\x18\x06 \x01(\x05R\tdeletions\"4\n" +
	"\n" +
	"CustomPart\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xc0\x02\n" +
	"\x04Part\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.llmsafespaces.abi.v1.PartTypeR\x04type\x12\x14\n" +
	"\x04text\x18\x03 \x01(\tH\x00R\x04text\x12\x1e\n" +
	"\treasoning\x18\x04 \x01(\tH\x00R\treasoning\x124\n" +
	"\x04tool\x18\x05 \x01(\v2\x1e.llmsafespaces.abi.v1.ToolPartH\x00R\x04tool\x12A\n" +
	"\vfile_change\x18\x06 \x01(\v2\x1e.llmsafespaces.abi.v1.FileDiffH\x00R\n" +
	"fileChange\x12:\n" +
	"\x06custom\x18\a \x01(\v2 .llmsafespaces.abi.v1.CustomPartH\x00R\x06customB\t\n" +
	"\apayload\"\xed\x05\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x125\n" +
	"\x04type\x18\x03 \x01(\x0e2!.llmsafespaces.abi.v1.MessageTypeR\x04type\x12>\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tcreatedAt\x88\x01\x01\x120\n" +
	"\x05parts\x18\x05 \x03(\v2\x1a.llmsafespaces.abi.v1.PartR\x05parts\x129\n" +
	"\x05model\x18\x06 \x01(\v2\x1e.llmsafespaces.abi.v1.ModelRefH\x01R\x05model\x88\x01\x01\x123\n" +
	"\x04cost\x18\a \x01(\v2\x1a.llmsafespaces.abi.v1.CostH\x02R\x04cost\x88\x01\x01\x12\x12\n" +
	"\x04text\x18\b \x01(\tR\x04text\x12\x18\n" +
	"\acommand\x18\t \x01(\tR\acommand\x12 \n" +
	"\texit_code\x18\n" +
	" \x01(\x05H\x03R\bexitCode\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"from_agent\x18\v \x01(\tR\tfromAgent\x12\x19\n" +
	"\bto_agent\x18\f \x01(\tR\atoAgent\x12B\n" +
	"\n" +
	"from_model\x18\r \x01(\v2\x1e.llmsafespaces.abi.v1.ModelRefH\x04R\tfromModel\x88\x01\x01\x12>\n" +
	"\bto_model\x18\x0e \x01(\v2\x1e.llmsafespaces.abi.v1.ModelRefH\x05R\atoModel\x88\x01\x01\x126\n" +
	"\x05error\x18\x0f \x01(\v2\x1b.llmsafespaces.abi.v1.ErrorH\x06R\x05error\x88\x01\x01B\r\n" +
	"\v_created_atB\b\n" +
	"\x06_modelB\a\n" +
	"\x05_costB\f\n" +
	"\n" +
	"_exit_codeB\r\n" +
	"\v_from_modelB\v\n" +
	"\t_to_modelB\b\n" +
	"\x06_error\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\vInputOption\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"A\n" +
	"\aToolRef\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"\xd1\x04\n" +
	"\fInputRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12&\n" +
	"\x0froot_session_id\x18\x03 \x01(\tR\rrootSessionId\x123\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1f.llmsafespaces.abi.v1.InputKindR\x04kind\x12\x1a\n" +
	"\bquestion\x18\x05 \x01(\tR\bquestion\x12\x16\n" +
	"\x06header\x18\x06 \x01(\tR\x06header\x12;\n" +
	"\aoptions\x18\a \x03(\v2!.llmsafespaces.abi.v1.InputOptionR\aoptions\x12\x1a\n" +
	"\bmultiple\x18\b \x01(\bR\bmultiple\x12\x16\n" +
	"\x06custom\x18\t \x01(\bR\x06custom\x12\x1e\n" +
	"\n" +
	"permission\x18\n" +
	" \x01(\tR\n" +
	"permission\x12\x1a\n" +
	"\bpatterns\x18\v \x03(\tR\bpatterns\x12\x16\n" +
	"\x06always\x18\f \x03(\tR\x06always\x12L\n" +
	"\bmetadata\x18\r \x03(\v20.llmsafespaces.abi.v1.InputRequest.MetadataEntryR\bmetadata\x121\n" +
	"\x04tool\x18\x0e \x01(\v2\x1d.llmsafespaces.abi.v1.ToolRefR\x04tool\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xaf\x04\n" +
	"\x05Event\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.llmsafespaces.abi.v1.EventTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12\x17\n" +
	"\apart_id\x18\x05 \x01(\tR\x06partId\x12;\n" +
	"\x06status\x18\x06 \x01(\x0e2#.llmsafespaces.abi.v1.SessionStatusR\x06status\x127\n" +
	"\asession\x18\a \x01(\v2\x1d.llmsafespaces.abi.v1.SessionR\asession\x127\n" +
	"\amessage\x18\b \x01(\v2\x1d.llmsafespaces.abi.v1.MessageR\amessage\x12.\n" +
	"\x04part\x18\t \x01(\v2\x1a.llmsafespaces.abi.v1.PartR\x04part\x12\x14\n" +
	"\x05delta\x18\n" +
	" \x01(\tR\x05delta\x128\n" +
	"\x05input\x18\v \x01(\v2\".llmsafespaces.abi.v1.InputRequestR\x05input\x121\n" +
	"\x05error\x18\f \x01(\v2\x1b.llmsafespaces.abi.v1.ErrorR\x05error*\xd3\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SESSION_STATUS_UNKNOWN\x10\x01\x12\x17\n" +
	"\x13SESSION_STATUS_IDLE\x10\x02\x12\x17\n" +
	"\x13SESSION_STATUS_BUSY\x10\x03\x12\x18\n" +
	"\x14SESSION_STATUS_ERROR\x10\x04\x12\x1d\n" +
	"\x19SESSION_STATUS_COMPACTING\x10\x05\x12\x1b\n" +
	"\x17SESSION_STATUS_ARCHIVED\x10\x06*\x97\x01\n" +
	"\bPartType\x12\x19\n" +
	"\x15PART_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePART_TYPE_TEXT\x10\x01\x12\x17\n" +
	"\x13PART_TYPE_REASONING\x10\x02\x12\x12\n" +
	"\x0ePART_TYPE_TOOL\x10\x03\x12\x19\n" +
	"\x15PART_TYPE_FILE_CHANGE\x10\x04\x12\x14\n" +
	"\x10PART_TYPE_CUSTOM\x10\x05*\x8d\x01\n" +
	"\n" +
	"ToolStatus\x12\x1b\n" +
	"\x17TOOL_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TOOL_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13TOOL_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15TOOL_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11TOOL_STATUS_ERROR\x10\x04*\x98\x01\n" +
	"\fChangeStatus\x12\x1d\n" +
	"\x19CHANGE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CHANGE_STATUS_ADDED\x10\x01\x12\x1a\n" +
	"\x16CHANGE_STATUS_MODIFIED\x10\x02\x12\x19\n" +
	"\x15CHANGE_STATUS_DELETED\x10\x03\x12\x19\n" +
	"\x15CHANGE_STATUS_RENAMED\x10\x04*\xea\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_USER\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_TYPE_ASSISTANT\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_SHELL\x10\x03\x12\x1d\n" +
	"\x19MESSAGE_TYPE_AGENT_SWITCH\x10\x04\x12\x1d\n" +
	"\x19MESSAGE_TYPE_MODEL_SWITCH\x10\x05\x12\x1b\n" +
	"\x17MESSAGE_TYPE_COMPACTION\x10\x06\x12\x17\n" +
	"\x13MESSAGE_TYPE_SYSTEM\x10\a*\xc2\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19EVENT_TYPE_SESSION_STATUS\x10\x01\x12\x1e\n" +
	"\x1aEVENT_TYPE_SESSION_UPDATED\x10\x02\x12\x1c\n" +
	"\x18EVENT_TYPE_MESSAGE_START\x10\x03\x12\x1a\n" +
	"\x16EVENT_TYPE_MESSAGE_END\x10\x04\x12\x19\n" +
	"\x15EVENT_TYPE_PART_START\x10\x05\x12\x19\n" +
	"\x15EVENT_TYPE_PART_DELTA\x10\x06\x12\x17\n" +
	"\x13EVENT_TYPE_PART_END\x10\a\x12\x1c\n" +
	"\x18EVENT_TYPE_INPUT_REQUEST\x10\b\x12\x1d\n" +
	"\x19EVENT_TYPE_INPUT_RESOLVED\x10\t\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\n" +
	"*[\n" +
	"\tInputKind\x12\x1a\n" +
	"\x16INPUT_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13INPUT_KIND_QUESTION\x10\x01\x12\x19\n" +
	"\x15INPUT_KIND_PERMISSION\x10\x02B1Z/github.com/lenaxia/llmsafespaces/pkg/abi/v1;abib\x06proto3"

var (
	file_llmsafespaces_abi_v1_contract_proto_rawDescOnce sync.Once
	file_llmsafespaces_abi_v1_contract_proto_rawDescData []byte
)

func file_llmsafespaces_abi_v1_contract_proto_rawDescGZIP() []byte {
	file_llmsafespaces_abi_v1_contract_proto_rawDescOnce.Do(func() {
		file_llmsafespaces_abi_v1_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_contract_proto_rawDesc), len(file_llmsafespaces_abi_v1_contract_proto_rawDesc)))
	})
	return file_llmsafespaces_abi_v1_contract_proto_rawDescData
}

var file_llmsafespaces_abi_v1_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_llmsafespaces_abi_v1_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_llmsafespaces_abi_v1_contract_proto_goTypes = []any{
	(SessionStatus)(0),            // 0: llmsafespaces.abi.v1.SessionStatus
	(PartType)(0),                 // 1: llmsafespaces.abi.v1.PartType
	(ToolStatus)(0),               // 2: llmsafespaces.abi.v1.ToolStatus
	(ChangeStatus)(0),             // 3: llmsafespaces.abi.v1.ChangeStatus
	(MessageType)(0),              // 4: llmsafespaces.abi.v1.MessageType
	(EventType)(0),                // 5: llmsafespaces.abi.v1.EventType
	(InputKind)(0),                // 6: llmsafespaces.abi.v1.InputKind
	(*TimeRange)(nil),             // 7: llmsafespaces.abi.v1.TimeRange
	(*Cost)(nil),                  // 8: llmsafespaces.abi.v1.Cost
	(*ContextUsage)(nil),          // 9: llmsafespaces.abi.v1.ContextUsage
	(*ModelRef)(nil),              // 10: llmsafespaces.abi.v1.ModelRef
	(*Session)(nil),               // 11: llmsafespaces.abi.v1.Session
	(*ToolState)(nil),             // 12: llmsafespaces.abi.v1.ToolState
	(*ToolPart)(nil),              // 13: llmsafespaces.abi.v1.ToolPart
	(*FileDiff)(nil),              // 14: llmsafespaces.abi.v1.FileDiff
	(*CustomPart)(nil),            // 15: llmsafespaces.abi.v1.CustomPart
	(*Part)(nil),                  // 16: llmsafespaces.abi.v1.Part
	(*Message)(nil),               // 17: llmsafespaces.abi.v1.Message
	(*Error)(nil),                 // 18: llmsafespaces.abi.v1.Error
	(*InputOption)(nil),           // 19: llmsafespaces.abi.v1.InputOption
	(*ToolRef)(nil),               // 20: llmsafespaces.abi.v1.ToolRef
	(*InputRequest)(nil),          // 21: llmsafespaces.abi.v1.InputRequest
	(*Event)(nil),                 // 22: llmsafespaces.abi.v1.Event
	nil,                           // 23: llmsafespaces.abi.v1.InputRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
}
var file_llmsafespaces_abi_v1_contract_proto_depIdxs = []int32{
	24, // 0: llmsafespaces.abi.v1.TimeRange.started_at:type_name -> google.protobuf.Timestamp
	24, // 1: llmsafespaces.abi.v1.TimeRange.completed_at:type_name -> google.protobuf.Timestamp
	10, // 2: llmsafespaces.abi.v1.Session.model:type_name -> llmsafespaces.abi.v1.ModelRef
	0,  // 3: llmsafespaces.abi.v1.Session.status:type_name -> llmsafespaces.abi.v1.SessionStatus
	8,  // 4: llmsafespaces.abi.v1.Session.cost:type_name -> llmsafespaces.abi.v1.Cost
	9,  // 5: llmsafespaces.abi.v1.Session.context_usage:type_name -> llmsafespaces.abi.v1.ContextUsage
	7,  // 6: llmsafespaces.abi.v1.Session.time:type_name -> llmsafespaces.abi.v1.TimeRange
	2,  // 7: llmsafespaces.abi.v1.ToolState.status:type_name -> llmsafespaces.abi.v1.ToolStatus
	24, // 8: llmsafespaces.abi.v1.ToolState.started_at:type_name -> google.protobuf.Timestamp
	24, // 9: llmsafespaces.abi.v1.ToolState.completed_at:type_name -> google.protobuf.Timestamp
	12, // 10: llmsafespaces.abi.v1.ToolPart.state:type_name -> llmsafespaces.abi.v1.ToolState
	3,  // 11: llmsafespaces.abi.v1.FileDiff.status:type_name -> llmsafespaces.abi.v1.ChangeStatus
	1,  // 12: llmsafespaces.abi.v1.Part.type:type_name -> llmsafespaces.abi.v1.PartType
	13, // 13: llmsafespaces.abi.v1.Part.tool:type_name -> llmsafespaces.abi.v1.ToolPart
	14, // 14: llmsafespaces.abi.v1.Part.file_change:type_name -> llmsafespaces.abi.v1.FileDiff
	15, // 15: llmsafespaces.abi.v1.Part.custom:type_name -> llmsafespaces.abi.v1.CustomPart
	4,  // 16: llmsafespaces.abi.v1.Message.type:type_name -> llmsafespaces.abi.v1.MessageType
	24, // 17: llmsafespaces.abi.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	16, // 18: llmsafespaces.abi.v1.Message.parts:type_name -> llmsafespaces.abi.v1.Part
	10, // 19: llmsafespaces.abi.v1.Message.model:type_name -> llmsafespaces.abi.v1.ModelRef
	8,  // 20: llmsafespaces.abi.v1.Message.cost:type_name -> llmsafespaces.abi.v1.Cost
	10, // 21: llmsafespaces.abi.v1.Message.from_model:type_name -> llmsafespaces.abi.v1.ModelRef
	10, // 22: llmsafespaces.abi.v1.Message.to_model:type_name -> llmsafespaces.abi.v1.ModelRef
	18, // 23: llmsafespaces.abi.v1.Message.error:type_name -> llmsafespaces.abi.v1.Error
	6,  // 24: llmsafespaces.abi.v1.InputRequest.kind:type_name -> llmsafespaces.abi.v1.InputKind
	19, // 25: llmsafespaces.abi.v1.InputRequest.options:type_name -> llmsafespaces.abi.v1.InputOption
	23, // 26: llmsafespaces.abi.v1.InputRequest.metadata:type_name -> llmsafespaces.abi.v1.InputRequest.MetadataEntry
	20, // 27: llmsafespaces.abi.v1.InputRequest.tool:type_name -> llmsafespaces.abi.v1.ToolRef
	5,  // 28: llmsafespaces.abi.v1.Event.type:type_name -> llmsafespaces.abi.v1.EventType
	24, // 29: llmsafespaces.abi.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 30: llmsafespaces.abi.v1.Event.status:type_name -> llmsafespaces.abi.v1.SessionStatus
	11, // 31: llmsafespaces.abi.v1.Event.session:type_name -> llmsafespaces.abi.v1.Session
	17, // 32: llmsafespaces.abi.v1.Event.message:type_name -> llmsafespaces.abi.v1.Message
	16, // 33: llmsafespaces.abi.v1.Event.part:type_name -> llmsafespaces.abi.v1.Part
	21, // 34: llmsafespaces.abi.v1.Event.input:type_name -> llmsafespaces.abi.v1.InputRequest
	18, // 35: llmsafespaces.abi.v1.Event.error:type_name -> llmsafespaces.abi.v1.Error
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_llmsafespaces_abi_v1_contract_proto_init() }
func file_llmsafespaces_abi_v1_contract_proto_init() {
	if File_llmsafespaces_abi_v1_contract_proto != nil {
		return
	}
	file_llmsafespaces_abi_v1_contract_proto_msgTypes[0].OneofWrappers = []any{}
	file_llmsafespaces_abi_v1_contract_proto_msgTypes[5].OneofWrappers = []any{}
	file_llmsafespaces_abi_v1_contract_proto_msgTypes[9].OneofWrappers = []any{
		(*Part_Text)(nil),
		(*Part_Reasoning)(nil),
		(*Part_Tool)(nil),
		(*Part_FileChange)(nil),
		(*Part_Custom)(nil),
	}
	file_llmsafespaces_abi_v1_contract_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_contract_proto_rawDesc), len(file_llmsafespaces_abi_v1_contract_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llmsafespaces_abi_v1_contract_proto_goTypes,
		DependencyIndexes: file_llmsafespaces_abi_v1_contract_proto_depIdxs,
		EnumInfos:         file_llmsafespaces_abi_v1_contract_proto_enumTypes,
		MessageInfos:      file_llmsafespaces_abi_v1_contract_proto_msgTypes,
	}.Build()
	File_llmsafespaces_abi_v1_contract_proto = out.File
	file_llmsafespaces_abi_v1_contract_proto_goTypes = nil
	file_llmsafespaces_abi_v1_contract_proto_depIdxs = nil
}
