// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Idempotent in-pod delivery over the agentd ledger (design 0055 M2).
// Dedupe scope is (entry_id, attempt): at-most-once admission per attempt,
// at-least-once effort overall. The delivery POST admits inline (D1-B) —
// 202 from agentd means "durably ledgered" (fsync before ack, I9), never
// "admitted to opencode".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: llmsafespaces/abi/v1/delivery.proto

package abi

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LedgerState is the M2 state machine:
// ledgered → admitted → promoted → turn-ended, with stalled (admitted past
// the promotion deadline — recovered by wake only, never re-admitted) and
// failed (per attempt — re-armable as (entry_id, attempt+1)).
type LedgerState int32

const (
	LedgerState_LEDGER_STATE_UNSPECIFIED LedgerState = 0
	LedgerState_LEDGER_STATE_LEDGERED    LedgerState = 1
	LedgerState_LEDGER_STATE_ADMITTED    LedgerState = 2
	LedgerState_LEDGER_STATE_PROMOTED    LedgerState = 3
	LedgerState_LEDGER_STATE_TURN_ENDED  LedgerState = 4
	LedgerState_LEDGER_STATE_STALLED     LedgerState = 5
	LedgerState_LEDGER_STATE_FAILED      LedgerState = 6
)

// Enum value maps for LedgerState.
var (
	LedgerState_name = map[int32]string{
		0: "LEDGER_STATE_UNSPECIFIED",
		1: "LEDGER_STATE_LEDGERED",
		2: "LEDGER_STATE_ADMITTED",
		3: "LEDGER_STATE_PROMOTED",
		4: "LEDGER_STATE_TURN_ENDED",
		5: "LEDGER_STATE_STALLED",
		6: "LEDGER_STATE_FAILED",
	}
	LedgerState_value = map[string]int32{
		"LEDGER_STATE_UNSPECIFIED": 0,
		"LEDGER_STATE_LEDGERED":    1,
		"LEDGER_STATE_ADMITTED":    2,
		"LEDGER_STATE_PROMOTED":    3,
		"LEDGER_STATE_TURN_ENDED":  4,
		"LEDGER_STATE_STALLED":     5,
		"LEDGER_STATE_FAILED":      6,
	}
)

func (x LedgerState) Enum() *LedgerState {
	p := new(LedgerState)
	*p = x
	return p
}

func (x LedgerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerState) Descriptor() protoreflect.EnumDescriptor {
	return file_llmsafespaces_abi_v1_delivery_proto_enumTypes[0].Descriptor()
}

func (LedgerState) Type() protoreflect.EnumType {
	return &file_llmsafespaces_abi_v1_delivery_proto_enumTypes[0]
}

func (x LedgerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerState.Descriptor instead.
func (LedgerState) EnumDescriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_delivery_proto_rawDescGZIP(), []int{0}
}

// FileReference points at a previously uploaded workspace file (Epic 68
// upload path shape: /workspace/uploads/<uuid>-<name>).
type FileReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReference) Reset() {
	*x = FileReference{}
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReference) ProtoMessage() {}

func (x *FileReference) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReference.ProtoReflect.Descriptor instead.
func (*FileReference) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *FileReference) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeliveryPart is one part of a delivery. The schema is parts-capable from
// day one (D3); harnesses that only accept text (opencode on 1.18.x) declare
// file parts NotSupported via the capability report — harness limits are
// data, not code branches. Multiple text parts are joined in order with
// newlines into the harness's text field (multi-text-part join rule).
type DeliveryPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Part:
	//
	//	*DeliveryPart_Text
	//	*DeliveryPart_File
	Part          isDeliveryPart_Part `protobuf_oneof:"part"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryPart) Reset() {
	*x = DeliveryPart{}
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryPart) ProtoMessage() {}

func (x *DeliveryPart) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryPart.ProtoReflect.Descriptor instead.
func (*DeliveryPart) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryPart) GetPart() isDeliveryPart_Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *DeliveryPart) GetText() string {
	if x != nil {
		if x, ok := x.Part.(*DeliveryPart_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *DeliveryPart) GetFile() *FileReference {
	if x != nil {
		if x, ok := x.Part.(*DeliveryPart_File); ok {
			return x.File
		}
	}
	return nil
}

type isDeliveryPart_Part interface {
	isDeliveryPart_Part()
}

type DeliveryPart_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type DeliveryPart_File struct {
	File *FileReference `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*DeliveryPart_Text) isDeliveryPart_Part() {}

func (*DeliveryPart_File) isDeliveryPart_Part() {}

// DeliveryRequest is the outbox's idempotent admission call. entry_id and
// attempt are outbox-controlled; agentd never invents them.
type DeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EntryId       string                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Attempt       uint32                 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Parts         []*DeliveryPart        `protobuf:"bytes,4,rep,name=parts,proto3" json:"parts,omitempty"`
	Model         *ModelRef              `protobuf:"bytes,5,opt,name=model,proto3,oneof" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryRequest) Reset() {
	*x = DeliveryRequest{}
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryRequest) ProtoMessage() {}

func (x *DeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryRequest.ProtoReflect.Descriptor instead.
func (*DeliveryRequest) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeliveryRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *DeliveryRequest) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *DeliveryRequest) GetParts() []*DeliveryPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *DeliveryRequest) GetModel() *ModelRef {
	if x != nil {
		return x.Model
	}
	return nil
}

// DeliveryAck confirms the entry is durably ledgered (I9). state is LEDGERED
// at ack time; later states are observable via GetDeliveryStatus.
type DeliveryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Attempt       uint32                 `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	State         LedgerState            `protobuf:"varint,3,opt,name=state,proto3,enum=llmsafespaces.abi.v1.LedgerState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAck) Reset() {
	*x = DeliveryAck{}
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAck) ProtoMessage() {}

func (x *DeliveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAck.ProtoReflect.Descriptor instead.
func (*DeliveryAck) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryAck) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *DeliveryAck) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *DeliveryAck) GetState() LedgerState {
	if x != nil {
		return x.State
	}
	return LedgerState_LEDGER_STATE_UNSPECIFIED
}

type GetDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EntryId       string                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Attempt       uint32                 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusRequest) Reset() {
	*x = GetDeliveryStatusRequest{}
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusRequest) ProtoMessage() {}

func (x *GetDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeliveryStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetDeliveryStatusRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *GetDeliveryStatusRequest) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

// DeliveryStatus is the per-(entry_id, attempt) ledger outcome — the
// replacement for the API-side text-scan verify oracle.
type DeliveryStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Attempt       uint32                 `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	State         LedgerState            `protobuf:"varint,3,opt,name=state,proto3,enum=llmsafespaces.abi.v1.LedgerState" json:"state,omitempty"`
	FailureReason string                 `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryStatus) Reset() {
	*x = DeliveryStatus{}
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStatus) ProtoMessage() {}

func (x *DeliveryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStatus.ProtoReflect.Descriptor instead.
func (*DeliveryStatus) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryStatus) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *DeliveryStatus) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *DeliveryStatus) GetState() LedgerState {
	if x != nil {
		return x.State
	}
	return LedgerState_LEDGER_STATE_UNSPECIFIED
}

func (x *DeliveryStatus) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *DeliveryStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_llmsafespaces_abi_v1_delivery_proto protoreflect.FileDescriptor

const file_llmsafespaces_abi_v1_delivery_proto_rawDesc = "" +
	"\n" +
	"#llmsafespaces/abi/v1/delivery.proto\x12\x14llmsafespaces.abi.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#llmsafespaces/abi/v1/contract.proto\"7\n" +
	"\rFileReference\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"g\n" +
	"\fDeliveryPart\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x129\n" +
	"\x04file\x18\x02 \x01(\v2#.llmsafespaces.abi.v1.FileReferenceH\x00R\x04fileB\x06\n" +
	"\x04part\"\xe4\x01\n" +
	"\x0fDeliveryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\tR\aentryId\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\rR\aattempt\x128\n" +
	"\x05parts\x18\x04 \x03(\v2\".llmsafespaces.abi.v1.DeliveryPartR\x05parts\x129\n" +
	"\x05model\x18\x05 \x01(\v2\x1e.llmsafespaces.abi.v1.ModelRefH\x00R\x05model\x88\x01\x01B\b\n" +
	"\x06_model\"{\n" +
	"\vDeliveryAck\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\rR\aattempt\x127\n" +
	"\x05state\x18\x03 \x01(\x0e2!.llmsafespaces.abi.v1.LedgerStateR\x05state\"n\n" +
	"\x18GetDeliveryStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\tR\aentryId\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\rR\aattempt\"\xf4\x01\n" +
	"\x0eDeliveryStatus\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\rR\aattempt\x127\n" +
	"\x05state\x18\x03 \x01(\x0e2!.llmsafespaces.abi.v1.LedgerStateR\x05state\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\x12>\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tupdatedAt\x88\x01\x01B\r\n" +
	"\v_updated_at*\xcc\x01\n" +
	"\vLedgerState\x12\x1c\n" +
	"\x18LEDGER_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LEDGER_STATE_LEDGERED\x10\x01\x12\x19\n" +
	"\x15LEDGER_STATE_ADMITTED\x10\x02\x12\x19\n" +
	"\x15LEDGER_STATE_PROMOTED\x10\x03\x12\x1b\n" +
	"\x17LEDGER_STATE_TURN_ENDED\x10\x04\x12\x18\n" +
	"\x14LEDGER_STATE_STALLED\x10\x05\x12\x17\n" +
	"\x13LEDGER_STATE_FAILED\x10\x06B1Z/github.com/lenaxia/llmsafespaces/pkg/abi/v1;abib\x06proto3"

var (
	file_llmsafespaces_abi_v1_delivery_proto_rawDescOnce sync.Once
	file_llmsafespaces_abi_v1_delivery_proto_rawDescData []byte
)

func file_llmsafespaces_abi_v1_delivery_proto_rawDescGZIP() []byte {
	file_llmsafespaces_abi_v1_delivery_proto_rawDescOnce.Do(func() {
		file_llmsafespaces_abi_v1_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_delivery_proto_rawDesc), len(file_llmsafespaces_abi_v1_delivery_proto_rawDesc)))
	})
	return file_llmsafespaces_abi_v1_delivery_proto_rawDescData
}

var file_llmsafespaces_abi_v1_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_llmsafespaces_abi_v1_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_llmsafespaces_abi_v1_delivery_proto_goTypes = []any{
	(LedgerState)(0),                 // 0: llmsafespaces.abi.v1.LedgerState
	(*FileReference)(nil),            // 1: llmsafespaces.abi.v1.FileReference
	(*DeliveryPart)(nil),             // 2: llmsafespaces.abi.v1.DeliveryPart
	(*DeliveryRequest)(nil),          // 3: llmsafespaces.abi.v1.DeliveryRequest
	(*DeliveryAck)(nil),              // 4: llmsafespaces.abi.v1.DeliveryAck
	(*GetDeliveryStatusRequest)(nil), // 5: llmsafespaces.abi.v1.GetDeliveryStatusRequest
	(*DeliveryStatus)(nil),           // 6: llmsafespaces.abi.v1.DeliveryStatus
	(*ModelRef)(nil),                 // 7: llmsafespaces.abi.v1.ModelRef
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_llmsafespaces_abi_v1_delivery_proto_depIdxs = []int32{
	1, // 0: llmsafespaces.abi.v1.DeliveryPart.file:type_name -> llmsafespaces.abi.v1.FileReference
	2, // 1: llmsafespaces.abi.v1.DeliveryRequest.parts:type_name -> llmsafespaces.abi.v1.DeliveryPart
	7, // 2: llmsafespaces.abi.v1.DeliveryRequest.model:type_name -> llmsafespaces.abi.v1.ModelRef
	0, // 3: llmsafespaces.abi.v1.DeliveryAck.state:type_name -> llmsafespaces.abi.v1.LedgerState
	0, // 4: llmsafespaces.abi.v1.DeliveryStatus.state:type_name -> llmsafespaces.abi.v1.LedgerState
	8, // 5: llmsafespaces.abi.v1.DeliveryStatus.updated_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_llmsafespaces_abi_v1_delivery_proto_init() }
func file_llmsafespaces_abi_v1_delivery_proto_init() {
	if File_llmsafespaces_abi_v1_delivery_proto != nil {
		return
	}
	file_llmsafespaces_abi_v1_contract_proto_init()
	file_llmsafespaces_abi_v1_delivery_proto_msgTypes[1].OneofWrappers = []any{
		(*DeliveryPart_Text)(nil),
		(*DeliveryPart_File)(nil),
	}
	file_llmsafespaces_abi_v1_delivery_proto_msgTypes[2].OneofWrappers = []any{}
	file_llmsafespaces_abi_v1_delivery_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_delivery_proto_rawDesc), len(file_llmsafespaces_abi_v1_delivery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llmsafespaces_abi_v1_delivery_proto_goTypes,
		DependencyIndexes: file_llmsafespaces_abi_v1_delivery_proto_depIdxs,
		EnumInfos:         file_llmsafespaces_abi_v1_delivery_proto_enumTypes,
		MessageInfos:      file_llmsafespaces_abi_v1_delivery_proto_msgTypes,
	}.Build()
	File_llmsafespaces_abi_v1_delivery_proto = out.File
	file_llmsafespaces_abi_v1_delivery_proto_goTypes = nil
	file_llmsafespaces_abi_v1_delivery_proto_depIdxs = nil
}
