// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Cursor-typed history (design 0055 §Harness ABI): history is DEFINED in
// the ABI but implemented for opencode only at S5, when upstream ships
// limit/before pagination on its message endpoint. New harnesses are
// ABI-native for history from day one. No RPC exists yet — S5 adds it as an
// additive surface extension; these message shapes freeze with the rest of
// the schema at S2 entrance so the op shape cannot drift in the meantime.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: llmsafespaces/abi/v1/history.proto

package abi

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cursor is opaque: clients pass it back verbatim and must not interpret it.
type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opaque        []byte                 `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_llmsafespaces_abi_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *Cursor) GetOpaque() []byte {
	if x != nil {
		return x.Opaque
	}
	return nil
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Before        *Cursor                `protobuf:"bytes,3,opt,name=before,proto3,oneof" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_llmsafespaces_abi_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HistoryRequest) GetBefore() *Cursor {
	if x != nil {
		return x.Before
	}
	return nil
}

type HistoryPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Next          *Cursor                `protobuf:"bytes,2,opt,name=next,proto3,oneof" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryPage) Reset() {
	*x = HistoryPage{}
	mi := &file_llmsafespaces_abi_v1_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryPage) ProtoMessage() {}

func (x *HistoryPage) ProtoReflect() protoreflect.Message {
	mi := &file_llmsafespaces_abi_v1_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryPage.ProtoReflect.Descriptor instead.
func (*HistoryPage) Descriptor() ([]byte, []int) {
	return file_llmsafespaces_abi_v1_history_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryPage) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *HistoryPage) GetNext() *Cursor {
	if x != nil {
		return x.Next
	}
	return nil
}

var File_llmsafespaces_abi_v1_history_proto protoreflect.FileDescriptor

const file_llmsafespaces_abi_v1_history_proto_rawDesc = "" +
	"\n" +
	"\"llmsafespaces/abi/v1/history.proto\x12\x14llmsafespaces.abi.v1\x1a#llmsafespaces/abi/v1/contract.proto\" \n" +
	"\x06Cursor\x12\x16\n" +
	"\x06opaque\x18\x01 \x01(\fR\x06opaque\"\x8b\x01\n" +
	"\x0eHistoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x129\n" +
	"\x06before\x18\x03 \x01(\v2\x1c.llmsafespaces.abi.v1.CursorH\x00R\x06before\x88\x01\x01B\t\n" +
	"\a_before\"\x88\x01\n" +
	"\vHistoryPage\x129\n" +
	"\bmessages\x18\x01 \x03(\v2\x1d.llmsafespaces.abi.v1.MessageR\bmessages\x125\n" +
	"\x04next\x18\x02 \x01(\v2\x1c.llmsafespaces.abi.v1.CursorH\x00R\x04next\x88\x01\x01B\a\n" +
	"\x05_nextB1Z/github.com/lenaxia/llmsafespaces/pkg/abi/v1;abib\x06proto3"

var (
	file_llmsafespaces_abi_v1_history_proto_rawDescOnce sync.Once
	file_llmsafespaces_abi_v1_history_proto_rawDescData []byte
)

func file_llmsafespaces_abi_v1_history_proto_rawDescGZIP() []byte {
	file_llmsafespaces_abi_v1_history_proto_rawDescOnce.Do(func() {
		file_llmsafespaces_abi_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_history_proto_rawDesc), len(file_llmsafespaces_abi_v1_history_proto_rawDesc)))
	})
	return file_llmsafespaces_abi_v1_history_proto_rawDescData
}

var file_llmsafespaces_abi_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_llmsafespaces_abi_v1_history_proto_goTypes = []any{
	(*Cursor)(nil),         // 0: llmsafespaces.abi.v1.Cursor
	(*HistoryRequest)(nil), // 1: llmsafespaces.abi.v1.HistoryRequest
	(*HistoryPage)(nil),    // 2: llmsafespaces.abi.v1.HistoryPage
	(*Message)(nil),        // 3: llmsafespaces.abi.v1.Message
}
var file_llmsafespaces_abi_v1_history_proto_depIdxs = []int32{
	0, // 0: llmsafespaces.abi.v1.HistoryRequest.before:type_name -> llmsafespaces.abi.v1.Cursor
	3, // 1: llmsafespaces.abi.v1.HistoryPage.messages:type_name -> llmsafespaces.abi.v1.Message
	0, // 2: llmsafespaces.abi.v1.HistoryPage.next:type_name -> llmsafespaces.abi.v1.Cursor
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_llmsafespaces_abi_v1_history_proto_init() }
func file_llmsafespaces_abi_v1_history_proto_init() {
	if File_llmsafespaces_abi_v1_history_proto != nil {
		return
	}
	file_llmsafespaces_abi_v1_contract_proto_init()
	file_llmsafespaces_abi_v1_history_proto_msgTypes[1].OneofWrappers = []any{}
	file_llmsafespaces_abi_v1_history_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmsafespaces_abi_v1_history_proto_rawDesc), len(file_llmsafespaces_abi_v1_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llmsafespaces_abi_v1_history_proto_goTypes,
		DependencyIndexes: file_llmsafespaces_abi_v1_history_proto_depIdxs,
		MessageInfos:      file_llmsafespaces_abi_v1_history_proto_msgTypes,
	}.Build()
	File_llmsafespaces_abi_v1_history_proto = out.File
	file_llmsafespaces_abi_v1_history_proto_goTypes = nil
	file_llmsafespaces_abi_v1_history_proto_depIdxs = nil
}
