// Copyright (C) 2026 Michael Kao
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The harness ABI — the entire outward surface of the agentd session-state
// authority (design 0055 M1): five operations in platform schema, frozen.
// If a change wants more than these ops, it belongs in the API.
//
// Sync protocol (M1): connect → snapshot@S → event@S+1 → event@S+2 …
// client rule: apply in order; discard seq ≤ S. There is no replay buffer
// and no since-cursor by design; reconnect mid-turn re-fetches in-flight
// state via a fresh stamped snapshot.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: llmsafespaces/abi/v1/abi.proto

package abiconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/lenaxia/llmsafespaces/pkg/abi/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HarnessABIServiceName is the fully-qualified name of the HarnessABIService service.
	HarnessABIServiceName = "llmsafespaces.abi.v1.HarnessABIService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HarnessABIServiceEventsProcedure is the fully-qualified name of the HarnessABIService's Events
	// RPC.
	HarnessABIServiceEventsProcedure = "/llmsafespaces.abi.v1.HarnessABIService/Events"
	// HarnessABIServiceGetSnapshotProcedure is the fully-qualified name of the HarnessABIService's
	// GetSnapshot RPC.
	HarnessABIServiceGetSnapshotProcedure = "/llmsafespaces.abi.v1.HarnessABIService/GetSnapshot"
	// HarnessABIServiceDeliverProcedure is the fully-qualified name of the HarnessABIService's Deliver
	// RPC.
	HarnessABIServiceDeliverProcedure = "/llmsafespaces.abi.v1.HarnessABIService/Deliver"
	// HarnessABIServiceGetDeliveryStatusProcedure is the fully-qualified name of the
	// HarnessABIService's GetDeliveryStatus RPC.
	HarnessABIServiceGetDeliveryStatusProcedure = "/llmsafespaces.abi.v1.HarnessABIService/GetDeliveryStatus"
	// HarnessABIServiceActProcedure is the fully-qualified name of the HarnessABIService's Act RPC.
	HarnessABIServiceActProcedure = "/llmsafespaces.abi.v1.HarnessABIService/Act"
)

// HarnessABIServiceClient is a client for the llmsafespaces.abi.v1.HarnessABIService service.
type HarnessABIServiceClient interface {
	// Op 1 — pod-wide event stream: one snapshot frame, then ordered live
	// events. Display only (D1-B); delivery never depends on it.
	Events(context.Context, *connect.Request[v1.EventsRequest]) (*connect.ServerStreamForClient[v1.StreamFrame], error)
	// Op 2 — session snapshot: busy/streaming state, in-flight parts with
	// partials, ledger-derived queue depth, pending question/permission
	// requests. Served from the projection with zero harness calls; a
	// snapshot alone is sufficient to render state and act (I12).
	GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.SessionSnapshot], error)
	// Op 3 — idempotent delivery admission (D1-B inline-first). Dedupe scope
	// is (entry_id, attempt); the ack implies durable ledger persistence.
	Deliver(context.Context, *connect.Request[v1.DeliveryRequest]) (*connect.Response[v1.DeliveryAck], error)
	// Op 4 — ledger outcome lookup for one outbox entry attempt.
	GetDeliveryStatus(context.Context, *connect.Request[v1.GetDeliveryStatusRequest]) (*connect.Response[v1.DeliveryStatus], error)
	// Op 5 — typed session actions, capability-negotiated.
	Act(context.Context, *connect.Request[v1.ActionRequest]) (*connect.Response[v1.ActionResult], error)
}

// NewHarnessABIServiceClient constructs a client for the llmsafespaces.abi.v1.HarnessABIService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHarnessABIServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HarnessABIServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	harnessABIServiceMethods := v1.File_llmsafespaces_abi_v1_abi_proto.Services().ByName("HarnessABIService").Methods()
	return &harnessABIServiceClient{
		events: connect.NewClient[v1.EventsRequest, v1.StreamFrame](
			httpClient,
			baseURL+HarnessABIServiceEventsProcedure,
			connect.WithSchema(harnessABIServiceMethods.ByName("Events")),
			connect.WithClientOptions(opts...),
		),
		getSnapshot: connect.NewClient[v1.GetSnapshotRequest, v1.SessionSnapshot](
			httpClient,
			baseURL+HarnessABIServiceGetSnapshotProcedure,
			connect.WithSchema(harnessABIServiceMethods.ByName("GetSnapshot")),
			connect.WithClientOptions(opts...),
		),
		deliver: connect.NewClient[v1.DeliveryRequest, v1.DeliveryAck](
			httpClient,
			baseURL+HarnessABIServiceDeliverProcedure,
			connect.WithSchema(harnessABIServiceMethods.ByName("Deliver")),
			connect.WithClientOptions(opts...),
		),
		getDeliveryStatus: connect.NewClient[v1.GetDeliveryStatusRequest, v1.DeliveryStatus](
			httpClient,
			baseURL+HarnessABIServiceGetDeliveryStatusProcedure,
			connect.WithSchema(harnessABIServiceMethods.ByName("GetDeliveryStatus")),
			connect.WithClientOptions(opts...),
		),
		act: connect.NewClient[v1.ActionRequest, v1.ActionResult](
			httpClient,
			baseURL+HarnessABIServiceActProcedure,
			connect.WithSchema(harnessABIServiceMethods.ByName("Act")),
			connect.WithClientOptions(opts...),
		),
	}
}

// harnessABIServiceClient implements HarnessABIServiceClient.
type harnessABIServiceClient struct {
	events            *connect.Client[v1.EventsRequest, v1.StreamFrame]
	getSnapshot       *connect.Client[v1.GetSnapshotRequest, v1.SessionSnapshot]
	deliver           *connect.Client[v1.DeliveryRequest, v1.DeliveryAck]
	getDeliveryStatus *connect.Client[v1.GetDeliveryStatusRequest, v1.DeliveryStatus]
	act               *connect.Client[v1.ActionRequest, v1.ActionResult]
}

// Events calls llmsafespaces.abi.v1.HarnessABIService.Events.
func (c *harnessABIServiceClient) Events(ctx context.Context, req *connect.Request[v1.EventsRequest]) (*connect.ServerStreamForClient[v1.StreamFrame], error) {
	return c.events.CallServerStream(ctx, req)
}

// GetSnapshot calls llmsafespaces.abi.v1.HarnessABIService.GetSnapshot.
func (c *harnessABIServiceClient) GetSnapshot(ctx context.Context, req *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.SessionSnapshot], error) {
	return c.getSnapshot.CallUnary(ctx, req)
}

// Deliver calls llmsafespaces.abi.v1.HarnessABIService.Deliver.
func (c *harnessABIServiceClient) Deliver(ctx context.Context, req *connect.Request[v1.DeliveryRequest]) (*connect.Response[v1.DeliveryAck], error) {
	return c.deliver.CallUnary(ctx, req)
}

// GetDeliveryStatus calls llmsafespaces.abi.v1.HarnessABIService.GetDeliveryStatus.
func (c *harnessABIServiceClient) GetDeliveryStatus(ctx context.Context, req *connect.Request[v1.GetDeliveryStatusRequest]) (*connect.Response[v1.DeliveryStatus], error) {
	return c.getDeliveryStatus.CallUnary(ctx, req)
}

// Act calls llmsafespaces.abi.v1.HarnessABIService.Act.
func (c *harnessABIServiceClient) Act(ctx context.Context, req *connect.Request[v1.ActionRequest]) (*connect.Response[v1.ActionResult], error) {
	return c.act.CallUnary(ctx, req)
}

// HarnessABIServiceHandler is an implementation of the llmsafespaces.abi.v1.HarnessABIService
// service.
type HarnessABIServiceHandler interface {
	// Op 1 — pod-wide event stream: one snapshot frame, then ordered live
	// events. Display only (D1-B); delivery never depends on it.
	Events(context.Context, *connect.Request[v1.EventsRequest], *connect.ServerStream[v1.StreamFrame]) error
	// Op 2 — session snapshot: busy/streaming state, in-flight parts with
	// partials, ledger-derived queue depth, pending question/permission
	// requests. Served from the projection with zero harness calls; a
	// snapshot alone is sufficient to render state and act (I12).
	GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.SessionSnapshot], error)
	// Op 3 — idempotent delivery admission (D1-B inline-first). Dedupe scope
	// is (entry_id, attempt); the ack implies durable ledger persistence.
	Deliver(context.Context, *connect.Request[v1.DeliveryRequest]) (*connect.Response[v1.DeliveryAck], error)
	// Op 4 — ledger outcome lookup for one outbox entry attempt.
	GetDeliveryStatus(context.Context, *connect.Request[v1.GetDeliveryStatusRequest]) (*connect.Response[v1.DeliveryStatus], error)
	// Op 5 — typed session actions, capability-negotiated.
	Act(context.Context, *connect.Request[v1.ActionRequest]) (*connect.Response[v1.ActionResult], error)
}

// NewHarnessABIServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHarnessABIServiceHandler(svc HarnessABIServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	harnessABIServiceMethods := v1.File_llmsafespaces_abi_v1_abi_proto.Services().ByName("HarnessABIService").Methods()
	harnessABIServiceEventsHandler := connect.NewServerStreamHandler(
		HarnessABIServiceEventsProcedure,
		svc.Events,
		connect.WithSchema(harnessABIServiceMethods.ByName("Events")),
		connect.WithHandlerOptions(opts...),
	)
	harnessABIServiceGetSnapshotHandler := connect.NewUnaryHandler(
		HarnessABIServiceGetSnapshotProcedure,
		svc.GetSnapshot,
		connect.WithSchema(harnessABIServiceMethods.ByName("GetSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	harnessABIServiceDeliverHandler := connect.NewUnaryHandler(
		HarnessABIServiceDeliverProcedure,
		svc.Deliver,
		connect.WithSchema(harnessABIServiceMethods.ByName("Deliver")),
		connect.WithHandlerOptions(opts...),
	)
	harnessABIServiceGetDeliveryStatusHandler := connect.NewUnaryHandler(
		HarnessABIServiceGetDeliveryStatusProcedure,
		svc.GetDeliveryStatus,
		connect.WithSchema(harnessABIServiceMethods.ByName("GetDeliveryStatus")),
		connect.WithHandlerOptions(opts...),
	)
	harnessABIServiceActHandler := connect.NewUnaryHandler(
		HarnessABIServiceActProcedure,
		svc.Act,
		connect.WithSchema(harnessABIServiceMethods.ByName("Act")),
		connect.WithHandlerOptions(opts...),
	)
	return "/llmsafespaces.abi.v1.HarnessABIService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HarnessABIServiceEventsProcedure:
			harnessABIServiceEventsHandler.ServeHTTP(w, r)
		case HarnessABIServiceGetSnapshotProcedure:
			harnessABIServiceGetSnapshotHandler.ServeHTTP(w, r)
		case HarnessABIServiceDeliverProcedure:
			harnessABIServiceDeliverHandler.ServeHTTP(w, r)
		case HarnessABIServiceGetDeliveryStatusProcedure:
			harnessABIServiceGetDeliveryStatusHandler.ServeHTTP(w, r)
		case HarnessABIServiceActProcedure:
			harnessABIServiceActHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHarnessABIServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHarnessABIServiceHandler struct{}

func (UnimplementedHarnessABIServiceHandler) Events(context.Context, *connect.Request[v1.EventsRequest], *connect.ServerStream[v1.StreamFrame]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("llmsafespaces.abi.v1.HarnessABIService.Events is not implemented"))
}

func (UnimplementedHarnessABIServiceHandler) GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.SessionSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llmsafespaces.abi.v1.HarnessABIService.GetSnapshot is not implemented"))
}

func (UnimplementedHarnessABIServiceHandler) Deliver(context.Context, *connect.Request[v1.DeliveryRequest]) (*connect.Response[v1.DeliveryAck], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llmsafespaces.abi.v1.HarnessABIService.Deliver is not implemented"))
}

func (UnimplementedHarnessABIServiceHandler) GetDeliveryStatus(context.Context, *connect.Request[v1.GetDeliveryStatusRequest]) (*connect.Response[v1.DeliveryStatus], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llmsafespaces.abi.v1.HarnessABIService.GetDeliveryStatus is not implemented"))
}

func (UnimplementedHarnessABIServiceHandler) Act(context.Context, *connect.Request[v1.ActionRequest]) (*connect.Response[v1.ActionResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("llmsafespaces.abi.v1.HarnessABIService.Act is not implemented"))
}
